//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 04:14:55 PM CEST 
//


package glueps.adaptors.vle.moodle.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}USERID"/>
 *         &lt;element ref="{}HIDDEN"/>
 *         &lt;element ref="{}TIMESTART"/>
 *         &lt;element ref="{}TIMEEND"/>
 *         &lt;element ref="{}TIMEMODIFIED"/>
 *         &lt;element ref="{}MODIFIERID"/>
 *         &lt;element ref="{}ENROL"/>
 *         &lt;element ref="{}SORTORDER"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userid",
    "hidden",
    "timestart",
    "timeend",
    "timemodified",
    "modifierid",
    "enrol",
    "sortorder"
})
@XmlRootElement(name = "ASSIGNMENT")
public class ASSIGNMENT implements Cloneable{

    @XmlElement(name = "USERID", required = true)
    protected BigInteger userid;
    @XmlElement(name = "HIDDEN", required = true)
    protected BigInteger hidden;
    @XmlElement(name = "TIMESTART", required = true)
    protected TIMESTART timestart;
    @XmlElement(name = "TIMEEND", required = true)
    protected TIMEEND timeend;
    @XmlElement(name = "TIMEMODIFIED", required = true)
    protected TIMEMODIFIED timemodified;
    @XmlElement(name = "MODIFIERID", required = true)
    protected BigInteger modifierid;
    @XmlElement(name = "ENROL", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String enrol;
    @XmlElement(name = "SORTORDER", required = true)
    protected BigInteger sortorder;

    /**
     * Gets the value of the userid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUSERID() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUSERID(BigInteger value) {
        this.userid = value;
    }

    /**
     * Gets the value of the hidden property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHIDDEN() {
        return hidden;
    }

    /**
     * Sets the value of the hidden property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHIDDEN(BigInteger value) {
        this.hidden = value;
    }

    /**
     * Gets the value of the timestart property.
     * 
     * @return
     *     possible object is
     *     {@link TIMESTART }
     *     
     */
    public TIMESTART getTIMESTART() {
        return timestart;
    }

    /**
     * Sets the value of the timestart property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIMESTART }
     *     
     */
    public void setTIMESTART(TIMESTART value) {
        this.timestart = value;
    }

    /**
     * Gets the value of the timeend property.
     * 
     * @return
     *     possible object is
     *     {@link TIMEEND }
     *     
     */
    public TIMEEND getTIMEEND() {
        return timeend;
    }

    /**
     * Sets the value of the timeend property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIMEEND }
     *     
     */
    public void setTIMEEND(TIMEEND value) {
        this.timeend = value;
    }

    /**
     * Gets the value of the timemodified property.
     * 
     * @return
     *     possible object is
     *     {@link TIMEMODIFIED }
     *     
     */
    public TIMEMODIFIED getTIMEMODIFIED() {
        return timemodified;
    }

    /**
     * Sets the value of the timemodified property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIMEMODIFIED }
     *     
     */
    public void setTIMEMODIFIED(TIMEMODIFIED value) {
        this.timemodified = value;
    }

    /**
     * Gets the value of the modifierid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMODIFIERID() {
        return modifierid;
    }

    /**
     * Sets the value of the modifierid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMODIFIERID(BigInteger value) {
        this.modifierid = value;
    }

    /**
     * Gets the value of the enrol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENROL() {
        return enrol;
    }

    /**
     * Sets the value of the enrol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENROL(String value) {
        this.enrol = value;
    }

    /**
     * Gets the value of the sortorder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSORTORDER() {
        return sortorder;
    }

    /**
     * Sets the value of the sortorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSORTORDER(BigInteger value) {
        this.sortorder = value;
    }
    public Object clone() 
    {
        Object clone = null;
         try 
         {
             clone = super.clone();
         }
         catch(CloneNotSupportedException e) 
         {
             // No debería ocurrir
         }
        return clone;
    }

}
