//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 04:14:55 PM CEST 
//


package glueps.adaptors.vle.moodle.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NAME"/>
 *         &lt;element ref="{}PERMISSION"/>
 *         &lt;element ref="{}TIMEMODIFIED"/>
 *         &lt;element ref="{}MODIFIERID"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "permission",
    "timemodified",
    "modifierid"
})
@XmlRootElement(name = "CAPABILITY")
public class CAPABILITY {

    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "PERMISSION", required = true)
    protected BigInteger permission;
    @XmlElement(name = "TIMEMODIFIED", required = true)
    protected TIMEMODIFIED timemodified;
    @XmlElement(name = "MODIFIERID", required = true)
    protected BigInteger modifierid;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the permission property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPERMISSION() {
        return permission;
    }

    /**
     * Sets the value of the permission property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPERMISSION(BigInteger value) {
        this.permission = value;
    }

    /**
     * Gets the value of the timemodified property.
     * 
     * @return
     *     possible object is
     *     {@link TIMEMODIFIED }
     *     
     */
    public TIMEMODIFIED getTIMEMODIFIED() {
        return timemodified;
    }

    /**
     * Sets the value of the timemodified property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIMEMODIFIED }
     *     
     */
    public void setTIMEMODIFIED(TIMEMODIFIED value) {
        this.timemodified = value;
    }

    /**
     * Gets the value of the modifierid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMODIFIERID() {
        return modifierid;
    }

    /**
     * Sets the value of the modifierid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMODIFIERID(BigInteger value) {
        this.modifierid = value;
    }

}
