//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 04:14:55 PM CEST 
//


package glueps.adaptors.vle.moodle.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ID" minOccurs="0"/>
 *         &lt;element ref="{}MODTYPE" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}TEMPLATE"/>
 *           &lt;element ref="{}DAYS"/>
 *         &lt;/sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}DESCRIPTION"/>
 *           &lt;element ref="{}FEEDBACK"/>
 *           &lt;element ref="{}FORMAT"/>
 *           &lt;element ref="{}LAUNCH"/>
 *           &lt;element ref="{}MAXANSWERS"/>
 *           &lt;element ref="{}MAXBYTES"/>
 *           &lt;element ref="{}MAXGRADE"/>
 *           &lt;element ref="{}NAME"/>
 *           &lt;element ref="{}PASSWORD"/>
 *           &lt;element ref="{}SUMMARY"/>
 *           &lt;element ref="{}TEXT"/>
 *           &lt;element ref="{}TIMECREATED"/>
 *           &lt;element ref="{}TIMEMODIFIED"/>
 *           &lt;element ref="{}TYPE"/>
 *           &lt;element ref="{}ACTIVITYLINK"/>
 *           &lt;element ref="{}ADDTEMPLATE"/>
 *           &lt;element ref="{}ALLOWCOMMENTS"/>
 *           &lt;element ref="{}ALLOWDUPLICATEDENTRIES"/>
 *           &lt;element ref="{}ALLOWPRINTVIEW"/>
 *           &lt;element ref="{}ALLOWUPDATE"/>
 *           &lt;element ref="{}ALLTEXT"/>
 *           &lt;element ref="{}APPROVAL"/>
 *           &lt;element ref="{}ASEARCHTEMPLATE"/>
 *           &lt;element ref="{}ASSESSED"/>
 *           &lt;element ref="{}ASSESSTIMEFINISH"/>
 *           &lt;element ref="{}ASSESSTIMESTART"/>
 *           &lt;element ref="{}ASSIGNMENTTYPE"/>
 *           &lt;element ref="{}ATTEMPTONLAST"/>
 *           &lt;element ref="{}ATTEMPTS_NUMBER"/>
 *           &lt;element ref="{}AUTO"/>
 *           &lt;element ref="{}AVAILABLE"/>
 *           &lt;element ref="{}BGCOLOR"/>
 *           &lt;element ref="{}CHATTIME"/>
 *           &lt;element ref="{}COMMENTS"/>
 *           &lt;element ref="{}CONDITIONS"/>
 *           &lt;element ref="{}CONTENT"/>
 *           &lt;element ref="{}CSSTEMPLATE"/>
 *           &lt;element ref="{}CUSTOM"/>
 *           &lt;element ref="{}DEADLINE"/>
 *           &lt;element ref="{}DECIMALPOINTS"/>
 *           &lt;element ref="{}DEFAULTAPPROVAL"/>
 *           &lt;element ref="{}DEPENDENCY"/>
 *           &lt;element ref="{}DISABLECAMELCASE"/>
 *           &lt;element ref="{}DISPLAY"/>
 *           &lt;element ref="{}DISPLAYFORMAT"/>
 *           &lt;element ref="{}DISPLAYLEFT"/>
 *           &lt;element ref="{}DISPLAYLEFTIF"/>
 *           &lt;element ref="{}EDITALWAYS"/>
 *           &lt;element ref="{}EMAILTEACHERS"/>
 *           &lt;element ref="{}ENTBYPAGE"/>
 *           &lt;element ref="{}EWIKIACCEPTBINARY"/>
 *           &lt;element ref="{}EWIKIPRINTTITLE"/>
 *           &lt;element ref="{}FORCESUBSCRIBE"/>
 *           &lt;element ref="{}GLOBALGLOSSARY"/>
 *           &lt;element ref="{}GRADE"/>
 *           &lt;element ref="{}GRADEMETHOD"/>
 *           &lt;element ref="{}HEIGHT"/>
 *           &lt;element ref="{}HIDEBROWSE"/>
 *           &lt;element ref="{}HIDENAV"/>
 *           &lt;element ref="{}HIDETOC"/>
 *           &lt;element ref="{}HTMLMODE"/>
 *           &lt;element ref="{}INITIALCONTENT"/>
 *           &lt;element ref="{}INTRO"/>
 *           &lt;element ref="{}JSTEMPLATE"/>
 *           &lt;element ref="{}KEEPDAYS"/>
 *           &lt;element ref="{}LIMITANSWERS"/>
 *           &lt;element ref="{}LISTTEMPLATE"/>
 *           &lt;element ref="{}LISTTEMPLATEFOOTER"/>
 *           &lt;element ref="{}LISTTEMPLATEHEADER"/>
 *           &lt;element ref="{}MAINGLOSSARY"/>
 *           &lt;element ref="{}MAXATTEMPT"/>
 *           &lt;element ref="{}MAXATTEMPTS"/>
 *           &lt;element ref="{}MAXENTRIES"/>
 *           &lt;element ref="{}MAXHIGHSCORES"/>
 *           &lt;element ref="{}MAXPAGES"/>
 *           &lt;element ref="{}MAXTIME"/>
 *           &lt;element ref="{}MD5HASH"/>
 *           &lt;element ref="{}MEDIACLOSE"/>
 *           &lt;element ref="{}MEDIAFILE"/>
 *           &lt;element ref="{}MEDIAHEIGHT"/>
 *           &lt;element ref="{}MEDIAWIDTH"/>
 *           &lt;element ref="{}MINQUESTIONS"/>
 *           &lt;element ref="{}MODATTEMPTS"/>
 *           &lt;element ref="{}NEXTPAGEDEFAULT"/>
 *           &lt;element ref="{}ONGOING"/>
 *           &lt;element ref="{}OPTIONFLAGS"/>
 *           &lt;element ref="{}OPTIONS"/>
 *           &lt;element ref="{}PAGENAME"/>
 *           &lt;element ref="{}PENALTYSCHEME"/>
 *           &lt;element ref="{}POPUP"/>
 *           &lt;element ref="{}PRACTICE"/>
 *           &lt;element ref="{}PREVENTLATE"/>
 *           &lt;element ref="{}PROGRESSBAR"/>
 *           &lt;element ref="{}PUBLISH"/>
 *           &lt;element ref="{}QUESTIONS"/>
 *           &lt;element ref="{}QUESTIONSPERPAGE"/>
 *           &lt;element ref="{}REFERENCE"/>
 *           &lt;element ref="{}REMOVEPAGES"/>
 *           &lt;element ref="{}REQUIREDENTRIES"/>
 *           &lt;element ref="{}REQUIREDENTRIESTOVIEW"/>
 *           &lt;element ref="{}RESUBMIT"/>
 *           &lt;element ref="{}RETAKE"/>
 *           &lt;element ref="{}REVERTCHANGES"/>
 *           &lt;element ref="{}REVIEW"/>
 *           &lt;element ref="{}RSSARTICLES"/>
 *           &lt;element ref="{}RSSTEMPLATE"/>
 *           &lt;element ref="{}RSSTITLETEMPLATE"/>
 *           &lt;element ref="{}RSSTYPE"/>
 *           &lt;element ref="{}SCALE"/>
 *           &lt;element ref="{}SCHEDULE"/>
 *           &lt;element ref="{}SETPAGEFLAGS"/>
 *           &lt;element ref="{}SHOWALL"/>
 *           &lt;element ref="{}SHOWALPHABET"/>
 *           &lt;element ref="{}SHOWHIGHSCORES"/>
 *           &lt;element ref="{}SHOWRESULTS"/>
 *           &lt;element ref="{}SHOWSPECIAL"/>
 *           &lt;element ref="{}SHOWUNANSWERED"/>
 *           &lt;element ref="{}SHUFFLEANSWERS"/>
 *           &lt;element ref="{}SHUFFLEQUESTIONS"/>
 *           &lt;element ref="{}SINGLETEMPLATE"/>
 *           &lt;element ref="{}SKIPVIEW"/>
 *           &lt;element ref="{}SLIDESHOW"/>
 *           &lt;element ref="{}STRIPPAGES"/>
 *           &lt;element ref="{}STUDENTLOGS"/>
 *           &lt;element ref="{}SUBNET"/>
 *           &lt;element ref="{}SUMGRADES"/>
 *           &lt;element ref="{}TIMEAVAILABLE"/>
 *           &lt;element ref="{}TIMEAVAILABLEFROM"/>
 *           &lt;element ref="{}TIMEAVAILABLETO"/>
 *           &lt;element ref="{}TIMECLOSE"/>
 *           &lt;element ref="{}TIMED"/>
 *           &lt;element ref="{}TIMEDUE"/>
 *           &lt;element ref="{}TIMELIMIT"/>
 *           &lt;element ref="{}TIMEOPEN"/>
 *           &lt;element ref="{}TIMEVIEWFROM"/>
 *           &lt;element ref="{}TIMEVIEWTO"/>
 *           &lt;element ref="{}TRACKINGTYPE"/>
 *           &lt;element ref="{}UPDATEFREQ"/>
 *           &lt;element ref="{}USEDYNALINK"/>
 *           &lt;element ref="{}USEMAXGRADE"/>
 *           &lt;element ref="{}USEPASSWORD"/>
 *           &lt;element ref="{}VAR1"/>
 *           &lt;element ref="{}VAR2"/>
 *           &lt;element ref="{}VAR3"/>
 *           &lt;element ref="{}VAR4"/>
 *           &lt;element ref="{}VAR5"/>
 *           &lt;element ref="{}VERSION"/>
 *           &lt;element ref="{}WIDTH"/>
 *           &lt;element ref="{}WTYPE"/>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}SCOES"/>
 *           &lt;sequence>
 *             &lt;element ref="{}DELAY1"/>
 *             &lt;element ref="{}DELAY2"/>
 *             &lt;element ref="{}FEEDBACKS"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{}INCLUDED"/>
 *             &lt;element ref="{}USERINFO"/>
 *             &lt;element ref="{}INSTANCES"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{}DEFAULTSORT"/>
 *             &lt;element ref="{}DEFAULTSORTDIR"/>
 *             &lt;element ref="{}EDITANY"/>
 *             &lt;element ref="{}NOTIFICATION"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{}INSTANCE"/>
 *             &lt;element ref="{}ADDED"/>
 *             &lt;element ref="{}SCORE"/>
 *             &lt;element ref="{}INDENT"/>
 *             &lt;element ref="{}VISIBLE"/>
 *             &lt;element ref="{}GROUPMODE"/>
 *             &lt;element ref="{}GROUPINGID"/>
 *             &lt;element ref="{}GROUPMEMBERSONLY"/>
 *             &lt;element ref="{}IDNUMBER"/>
 *             &lt;element ref="{}ROLES_OVERRIDES"/>
 *             &lt;element ref="{}ROLES_ASSIGNMENTS"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{}WARNAFTER"/>
 *             &lt;element ref="{}BLOCKAFTER"/>
 *             &lt;element ref="{}BLOCKPERIOD"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "modtype",
    "template",
    "days",
    "descriptionOrFEEDBACKOrFORMAT",
    "scoes",
    "delay1",
    "delay2",
    "feedbacks",
    "included",
    "userinfo",
    "instances",
    "defaultsort",
    "defaultsortdir",
    "editany",
    "notification",
    "instance",
    "added",
    "score",
    "indent",
    "visible",
    "groupmode",
    "groupingid",
    "groupmembersonly",
    "idnumber",
    "rolesoverrides",
    "rolesassignments",
    "warnafter",
    "blockafter",
    "blockperiod"
})
@XmlRootElement(name = "MOD")
public class CopyOfMOD implements Cloneable{

    @XmlElement(name = "ID")
    protected BigInteger id;
    @XmlElement(name = "MODTYPE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String modtype;
    @XmlElement(name = "TEMPLATE")
    protected BigInteger template;
    @XmlElement(name = "DAYS")
    protected BigInteger days;
    @XmlElementRefs({
        @XmlElementRef(name = "MAXATTEMPTS", type = JAXBElement.class),
        @XmlElementRef(name = "HIDETOC", type = JAXBElement.class),
        @XmlElementRef(name = "SETPAGEFLAGS", type = JAXBElement.class),
        @XmlElementRef(name = "ATTEMPTS_NUMBER", type = JAXBElement.class),
        @XmlElementRef(name = "ALLOWDUPLICATEDENTRIES", type = JAXBElement.class),
        @XmlElementRef(name = "SLIDESHOW", type = JAXBElement.class),
        @XmlElementRef(name = "ENTBYPAGE", type = JAXBElement.class),
        @XmlElementRef(name = "CONTENT", type = JAXBElement.class),
        @XmlElementRef(name = "APPROVAL", type = JAXBElement.class),
        @XmlElementRef(name = "ASSIGNMENTTYPE", type = JAXBElement.class),
        @XmlElementRef(name = "RESUBMIT", type = JAXBElement.class),
        @XmlElementRef(name = "CONDITIONS", type = JAXBElement.class),
        @XmlElementRef(name = "MAXBYTES", type = JAXBElement.class),
        @XmlElementRef(name = "MD5HASH", type = JAXBElement.class),
        @XmlElementRef(name = "SCHEDULE", type = JAXBElement.class),
        @XmlElementRef(name = "LAUNCH", type = JAXBElement.class),
        @XmlElementRef(name = "RSSARTICLES", type = JAXBElement.class),
        @XmlElementRef(name = "UPDATEFREQ", type = JAXBElement.class),
        @XmlElementRef(name = "REQUIREDENTRIES", type = JAXBElement.class),
        @XmlElementRef(name = "TIMECREATED", type = TIMECREATED.class),
        @XmlElementRef(name = "MAXTIME", type = JAXBElement.class),
        @XmlElementRef(name = "TIMECLOSE", type = JAXBElement.class),
        @XmlElementRef(name = "MINQUESTIONS", type = JAXBElement.class),
        @XmlElementRef(name = "ADDTEMPLATE", type = JAXBElement.class),
        @XmlElementRef(name = "QUESTIONS", type = JAXBElement.class),
        @XmlElementRef(name = "LIMITANSWERS", type = JAXBElement.class),
        @XmlElementRef(name = "CSSTEMPLATE", type = JAXBElement.class),
        @XmlElementRef(name = "DECIMALPOINTS", type = JAXBElement.class),
        @XmlElementRef(name = "SHOWUNANSWERED", type = JAXBElement.class),
        @XmlElementRef(name = "TIMEAVAILABLEFROM", type = JAXBElement.class),
        @XmlElementRef(name = "MAXANSWERS", type = JAXBElement.class),
        @XmlElementRef(name = "POPUP", type = JAXBElement.class),
        @XmlElementRef(name = "SCALE", type = JAXBElement.class),
        @XmlElementRef(name = "WIDTH", type = JAXBElement.class),
        @XmlElementRef(name = "DISPLAYFORMAT", type = JAXBElement.class),
        @XmlElementRef(name = "PREVENTLATE", type = JAXBElement.class),
        @XmlElementRef(name = "GRADE", type = JAXBElement.class),
        @XmlElementRef(name = "REVIEW", type = JAXBElement.class),
        @XmlElementRef(name = "PROGRESSBAR", type = JAXBElement.class),
        @XmlElementRef(name = "JSTEMPLATE", type = JAXBElement.class),
        @XmlElementRef(name = "REQUIREDENTRIESTOVIEW", type = JAXBElement.class),
        @XmlElementRef(name = "ALLOWUPDATE", type = JAXBElement.class),
        @XmlElementRef(name = "DISPLAY", type = JAXBElement.class),
        @XmlElementRef(name = "NEXTPAGEDEFAULT", type = JAXBElement.class),
        @XmlElementRef(name = "REVERTCHANGES", type = JAXBElement.class),
        @XmlElementRef(name = "DESCRIPTION", type = JAXBElement.class),
        @XmlElementRef(name = "DEADLINE", type = JAXBElement.class),
        @XmlElementRef(name = "HIDENAV", type = JAXBElement.class),
        @XmlElementRef(name = "EMAILTEACHERS", type = JAXBElement.class),
        @XmlElementRef(name = "STRIPPAGES", type = JAXBElement.class),
        @XmlElementRef(name = "PASSWORD", type = PASSWORD.class),
        @XmlElementRef(name = "SUMGRADES", type = JAXBElement.class),
        @XmlElementRef(name = "MODATTEMPTS", type = JAXBElement.class),
        @XmlElementRef(name = "KEEPDAYS", type = JAXBElement.class),
        @XmlElementRef(name = "SKIPVIEW", type = JAXBElement.class),
        @XmlElementRef(name = "SHUFFLEANSWERS", type = JAXBElement.class),
        @XmlElementRef(name = "SHOWALPHABET", type = JAXBElement.class),
        @XmlElementRef(name = "AUTO", type = JAXBElement.class),
        @XmlElementRef(name = "FORMAT", type = JAXBElement.class),
        @XmlElementRef(name = "TIMEVIEWFROM", type = JAXBElement.class),
        @XmlElementRef(name = "LISTTEMPLATE", type = JAXBElement.class),
        @XmlElementRef(name = "RSSTEMPLATE", type = JAXBElement.class),
        @XmlElementRef(name = "SHOWRESULTS", type = JAXBElement.class),
        @XmlElementRef(name = "DISPLAYLEFT", type = JAXBElement.class),
        @XmlElementRef(name = "COMMENTS", type = JAXBElement.class),
        @XmlElementRef(name = "MAXATTEMPT", type = JAXBElement.class),
        @XmlElementRef(name = "FEEDBACK", type = FEEDBACK.class),
        @XmlElementRef(name = "FORCESUBSCRIBE", type = JAXBElement.class),
        @XmlElementRef(name = "DISABLECAMELCASE", type = JAXBElement.class),
        @XmlElementRef(name = "HTMLMODE", type = JAXBElement.class),
        @XmlElementRef(name = "RSSTITLETEMPLATE", type = JAXBElement.class),
        @XmlElementRef(name = "SHOWSPECIAL", type = JAXBElement.class),
        @XmlElementRef(name = "EDITALWAYS", type = JAXBElement.class),
        @XmlElementRef(name = "MEDIAHEIGHT", type = JAXBElement.class),
        @XmlElementRef(name = "TIMED", type = JAXBElement.class),
        @XmlElementRef(name = "ASSESSTIMESTART", type = JAXBElement.class),
        @XmlElementRef(name = "WTYPE", type = JAXBElement.class),
        @XmlElementRef(name = "HEIGHT", type = JAXBElement.class),
        @XmlElementRef(name = "TIMEMODIFIED", type = TIMEMODIFIED.class),
        @XmlElementRef(name = "RSSTYPE", type = JAXBElement.class),
        @XmlElementRef(name = "GLOBALGLOSSARY", type = JAXBElement.class),
        @XmlElementRef(name = "GRADEMETHOD", type = JAXBElement.class),
        @XmlElementRef(name = "ALLOWCOMMENTS", type = JAXBElement.class),
        @XmlElementRef(name = "PAGENAME", type = JAXBElement.class),
        @XmlElementRef(name = "QUESTIONSPERPAGE", type = JAXBElement.class),
        @XmlElementRef(name = "ATTEMPTONLAST", type = JAXBElement.class),
        @XmlElementRef(name = "MAXENTRIES", type = JAXBElement.class),
        @XmlElementRef(name = "TIMEVIEWTO", type = JAXBElement.class),
        @XmlElementRef(name = "OPTIONFLAGS", type = JAXBElement.class),
        @XmlElementRef(name = "DEFAULTAPPROVAL", type = JAXBElement.class),
        @XmlElementRef(name = "VAR3", type = JAXBElement.class),
        @XmlElementRef(name = "TIMEOPEN", type = JAXBElement.class),
        @XmlElementRef(name = "DISPLAYLEFTIF", type = JAXBElement.class),
        @XmlElementRef(name = "VAR5", type = JAXBElement.class),
        @XmlElementRef(name = "TIMEDUE", type = JAXBElement.class),
        @XmlElementRef(name = "EWIKIACCEPTBINARY", type = JAXBElement.class),
        @XmlElementRef(name = "MAXGRADE", type = JAXBElement.class),
        @XmlElementRef(name = "ASSESSED", type = JAXBElement.class),
        @XmlElementRef(name = "OPTIONS", type = OPTIONS.class),
        @XmlElementRef(name = "SUMMARY", type = JAXBElement.class),
        @XmlElementRef(name = "TIMEAVAILABLE", type = JAXBElement.class),
        @XmlElementRef(name = "PUBLISH", type = JAXBElement.class),
        @XmlElementRef(name = "BGCOLOR", type = JAXBElement.class),
        @XmlElementRef(name = "SHUFFLEQUESTIONS", type = JAXBElement.class),
        @XmlElementRef(name = "EWIKIPRINTTITLE", type = JAXBElement.class),
        @XmlElementRef(name = "SHOWHIGHSCORES", type = JAXBElement.class),
        @XmlElementRef(name = "MEDIAFILE", type = MEDIAFILE.class),
        @XmlElementRef(name = "USEMAXGRADE", type = JAXBElement.class),
        @XmlElementRef(name = "SUBNET", type = SUBNET.class),
        @XmlElementRef(name = "PRACTICE", type = JAXBElement.class),
        @XmlElementRef(name = "ALLOWPRINTVIEW", type = JAXBElement.class),
        @XmlElementRef(name = "RETAKE", type = JAXBElement.class),
        @XmlElementRef(name = "ASSESSTIMEFINISH", type = JAXBElement.class),
        @XmlElementRef(name = "TYPE", type = JAXBElement.class),
        @XmlElementRef(name = "SHOWALL", type = JAXBElement.class),
        @XmlElementRef(name = "REFERENCE", type = JAXBElement.class),
        @XmlElementRef(name = "AVAILABLE", type = JAXBElement.class),
        @XmlElementRef(name = "VERSION", type = JAXBElement.class),
        @XmlElementRef(name = "LISTTEMPLATEHEADER", type = JAXBElement.class),
        @XmlElementRef(name = "DEPENDENCY", type = JAXBElement.class),
        @XmlElementRef(name = "NAME", type = JAXBElement.class),
        @XmlElementRef(name = "INITIALCONTENT", type = INITIALCONTENT.class),
        @XmlElementRef(name = "TIMEAVAILABLETO", type = JAXBElement.class),
        @XmlElementRef(name = "TEXT", type = JAXBElement.class),
        @XmlElementRef(name = "STUDENTLOGS", type = JAXBElement.class),
        @XmlElementRef(name = "MAXPAGES", type = JAXBElement.class),
        @XmlElementRef(name = "INTRO", type = JAXBElement.class),
        @XmlElementRef(name = "SINGLETEMPLATE", type = JAXBElement.class),
        @XmlElementRef(name = "HIDEBROWSE", type = JAXBElement.class),
        @XmlElementRef(name = "VAR2", type = JAXBElement.class),
        @XmlElementRef(name = "ACTIVITYLINK", type = JAXBElement.class),
        @XmlElementRef(name = "MAXHIGHSCORES", type = JAXBElement.class),
        @XmlElementRef(name = "CHATTIME", type = JAXBElement.class),
        @XmlElementRef(name = "PENALTYSCHEME", type = JAXBElement.class),
        @XmlElementRef(name = "CUSTOM", type = JAXBElement.class),
        @XmlElementRef(name = "TRACKINGTYPE", type = JAXBElement.class),
        @XmlElementRef(name = "MEDIAWIDTH", type = JAXBElement.class),
        @XmlElementRef(name = "USEDYNALINK", type = JAXBElement.class),
        @XmlElementRef(name = "USEPASSWORD", type = JAXBElement.class),
        @XmlElementRef(name = "VAR1", type = JAXBElement.class),
        @XmlElementRef(name = "MAINGLOSSARY", type = JAXBElement.class),
        @XmlElementRef(name = "ONGOING", type = JAXBElement.class),
        @XmlElementRef(name = "TIMELIMIT", type = JAXBElement.class),
        @XmlElementRef(name = "MEDIACLOSE", type = JAXBElement.class),
        @XmlElementRef(name = "REMOVEPAGES", type = JAXBElement.class),
        @XmlElementRef(name = "VAR4", type = JAXBElement.class),
        @XmlElementRef(name = "LISTTEMPLATEFOOTER", type = JAXBElement.class),
        @XmlElementRef(name = "ALLTEXT", type = JAXBElement.class),
        @XmlElementRef(name = "ASEARCHTEMPLATE", type = JAXBElement.class)
    })
    protected List<Object> descriptionOrFEEDBACKOrFORMAT;
    @XmlElement(name = "SCOES")
    protected SCOES scoes;
    @XmlElement(name = "DELAY1")
    protected BigInteger delay1;
    @XmlElement(name = "DELAY2")
    protected BigInteger delay2;
    @XmlElement(name = "FEEDBACKS")
    protected FEEDBACKS feedbacks;
    @XmlElement(name = "INCLUDED")
    protected Boolean included;
    @XmlElement(name = "USERINFO")
    protected Boolean userinfo;
    @XmlElement(name = "INSTANCES")
    protected INSTANCES instances;
    @XmlElement(name = "DEFAULTSORT")
    protected BigInteger defaultsort;
    @XmlElement(name = "DEFAULTSORTDIR")
    protected BigInteger defaultsortdir;
    @XmlElement(name = "EDITANY")
    protected BigInteger editany;
    @XmlElement(name = "NOTIFICATION")
    protected BigInteger notification;
    @XmlElement(name = "INSTANCE")
    protected INSTANCE instance;
    @XmlElement(name = "ADDED")
    protected BigInteger added;
    @XmlElement(name = "SCORE")
    protected BigInteger score;
    @XmlElement(name = "INDENT")
    protected BigInteger indent;
    @XmlElement(name = "VISIBLE")
    protected BigInteger visible;
    @XmlElement(name = "GROUPMODE")
    protected BigInteger groupmode;
    @XmlElement(name = "GROUPINGID")
    protected BigInteger groupingid;
    @XmlElement(name = "GROUPMEMBERSONLY")
    protected BigInteger groupmembersonly;
    @XmlElement(name = "IDNUMBER")
    protected String idnumber;
    @XmlElement(name = "ROLES_OVERRIDES")
    protected ROLESOVERRIDES rolesoverrides;
    @XmlElement(name = "ROLES_ASSIGNMENTS")
    protected ROLESASSIGNMENTS rolesassignments;
    @XmlElement(name = "WARNAFTER")
    protected BigInteger warnafter;
    @XmlElement(name = "BLOCKAFTER")
    protected BigInteger blockafter;
    @XmlElement(name = "BLOCKPERIOD")
    protected BigInteger blockperiod;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the modtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMODTYPE() {
        return modtype;
    }

    /**
     * Sets the value of the modtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMODTYPE(String value) {
        this.modtype = value;
    }

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTEMPLATE() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTEMPLATE(BigInteger value) {
        this.template = value;
    }

    /**
     * Gets the value of the days property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDAYS() {
        return days;
    }

    /**
     * Sets the value of the days property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDAYS(BigInteger value) {
        this.days = value;
    }

    /**
     * Gets the value of the descriptionOrFEEDBACKOrFORMAT property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descriptionOrFEEDBACKOrFORMAT property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDESCRIPTIONOrFEEDBACKOrFORMAT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link TIMECREATED }
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link PASSWORD }
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link FEEDBACK }
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link TIMEMODIFIED }
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link OPTIONS }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link MEDIAFILE }
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link SUBNET }
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link INITIALCONTENT }
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getDESCRIPTIONOrFEEDBACKOrFORMAT() {
        if (descriptionOrFEEDBACKOrFORMAT == null) {
            descriptionOrFEEDBACKOrFORMAT = new ArrayList<Object>();
        }
        return this.descriptionOrFEEDBACKOrFORMAT;
    }

    public void setDESCRIPTIONOrFEEDBACKOrFORMAT(List<Object> value) {
            descriptionOrFEEDBACKOrFORMAT = value;

    }
    
    
    /**
     * Gets the value of the scoes property.
     * 
     * @return
     *     possible object is
     *     {@link SCOES }
     *     
     */
    public SCOES getSCOES() {
        return scoes;
    }

    /**
     * Sets the value of the scoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCOES }
     *     
     */
    public void setSCOES(SCOES value) {
        this.scoes = value;
    }

    /**
     * Gets the value of the delay1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDELAY1() {
        return delay1;
    }

    /**
     * Sets the value of the delay1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDELAY1(BigInteger value) {
        this.delay1 = value;
    }

    /**
     * Gets the value of the delay2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDELAY2() {
        return delay2;
    }

    /**
     * Sets the value of the delay2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDELAY2(BigInteger value) {
        this.delay2 = value;
    }

    /**
     * Gets the value of the feedbacks property.
     * 
     * @return
     *     possible object is
     *     {@link FEEDBACKS }
     *     
     */
    public FEEDBACKS getFEEDBACKS() {
        return feedbacks;
    }

    /**
     * Sets the value of the feedbacks property.
     * 
     * @param value
     *     allowed object is
     *     {@link FEEDBACKS }
     *     
     */
    public void setFEEDBACKS(FEEDBACKS value) {
        this.feedbacks = value;
    }

    /**
     * Gets the value of the included property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isINCLUDED() {
        return included;
    }

    /**
     * Sets the value of the included property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setINCLUDED(Boolean value) {
        this.included = value;
    }

    /**
     * Gets the value of the userinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUSERINFO() {
        return userinfo;
    }

    /**
     * Sets the value of the userinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUSERINFO(Boolean value) {
        this.userinfo = value;
    }

    /**
     * Gets the value of the instances property.
     * 
     * @return
     *     possible object is
     *     {@link INSTANCES }
     *     
     */
    public INSTANCES getINSTANCES() {
        return instances;
    }

    /**
     * Sets the value of the instances property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSTANCES }
     *     
     */
    public void setINSTANCES(INSTANCES value) {
        this.instances = value;
    }

    /**
     * Gets the value of the defaultsort property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDEFAULTSORT() {
        return defaultsort;
    }

    /**
     * Sets the value of the defaultsort property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDEFAULTSORT(BigInteger value) {
        this.defaultsort = value;
    }

    /**
     * Gets the value of the defaultsortdir property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDEFAULTSORTDIR() {
        return defaultsortdir;
    }

    /**
     * Sets the value of the defaultsortdir property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDEFAULTSORTDIR(BigInteger value) {
        this.defaultsortdir = value;
    }

    /**
     * Gets the value of the editany property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEDITANY() {
        return editany;
    }

    /**
     * Sets the value of the editany property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEDITANY(BigInteger value) {
        this.editany = value;
    }

    /**
     * Gets the value of the notification property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNOTIFICATION() {
        return notification;
    }

    /**
     * Sets the value of the notification property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNOTIFICATION(BigInteger value) {
        this.notification = value;
    }

    /**
     * Gets the value of the instance property.
     * 
     * @return
     *     possible object is
     *     {@link INSTANCE }
     *     
     */
    public INSTANCE getINSTANCE() {
        return instance;
    }

    /**
     * Sets the value of the instance property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSTANCE }
     *     
     */
    public void setINSTANCE(INSTANCE value) {
        this.instance = value;
    }

    /**
     * Gets the value of the added property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getADDED() {
        return added;
    }

    /**
     * Sets the value of the added property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setADDED(BigInteger value) {
        this.added = value;
    }

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSCORE() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSCORE(BigInteger value) {
        this.score = value;
    }

    /**
     * Gets the value of the indent property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getINDENT() {
        return indent;
    }

    /**
     * Sets the value of the indent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setINDENT(BigInteger value) {
        this.indent = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVISIBLE() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVISIBLE(BigInteger value) {
        this.visible = value;
    }

    /**
     * Gets the value of the groupmode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGROUPMODE() {
        return groupmode;
    }

    /**
     * Sets the value of the groupmode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGROUPMODE(BigInteger value) {
        this.groupmode = value;
    }

    /**
     * Gets the value of the groupingid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGROUPINGID() {
        return groupingid;
    }

    /**
     * Sets the value of the groupingid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGROUPINGID(BigInteger value) {
        this.groupingid = value;
    }

    /**
     * Gets the value of the groupmembersonly property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGROUPMEMBERSONLY() {
        return groupmembersonly;
    }

    /**
     * Sets the value of the groupmembersonly property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGROUPMEMBERSONLY(BigInteger value) {
        this.groupmembersonly = value;
    }

    /**
     * Gets the value of the idnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDNUMBER() {
        return idnumber;
    }

    /**
     * Sets the value of the idnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDNUMBER(String value) {
        this.idnumber = value;
    }

    /**
     * Gets the value of the rolesoverrides property.
     * 
     * @return
     *     possible object is
     *     {@link ROLESOVERRIDES }
     *     
     */
    public ROLESOVERRIDES getROLESOVERRIDES() {
        return rolesoverrides;
    }

    /**
     * Sets the value of the rolesoverrides property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROLESOVERRIDES }
     *     
     */
    public void setROLESOVERRIDES(ROLESOVERRIDES value) {
        this.rolesoverrides = value;
    }

    /**
     * Gets the value of the rolesassignments property.
     * 
     * @return
     *     possible object is
     *     {@link ROLESASSIGNMENTS }
     *     
     */
    public ROLESASSIGNMENTS getROLESASSIGNMENTS() {
        return rolesassignments;
    }

    /**
     * Sets the value of the rolesassignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROLESASSIGNMENTS }
     *     
     */
    public void setROLESASSIGNMENTS(ROLESASSIGNMENTS value) {
        this.rolesassignments = value;
    }

    /**
     * Gets the value of the warnafter property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWARNAFTER() {
        return warnafter;
    }

    /**
     * Sets the value of the warnafter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWARNAFTER(BigInteger value) {
        this.warnafter = value;
    }

    /**
     * Gets the value of the blockafter property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBLOCKAFTER() {
        return blockafter;
    }

    /**
     * Sets the value of the blockafter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBLOCKAFTER(BigInteger value) {
        this.blockafter = value;
    }

    /**
     * Gets the value of the blockperiod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBLOCKPERIOD() {
        return blockperiod;
    }

    /**
     * Sets the value of the blockperiod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBLOCKPERIOD(BigInteger value) {
        this.blockperiod = value;
    }
    public Object clone() 
    {
        Object clone = null;
         try 
         {
             clone = super.clone();
         }
         catch(CloneNotSupportedException e) 
         {
             // No debería ocurrir
         }
        return clone;
    }
}
