//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 04:14:55 PM CEST 
//


package glueps.adaptors.vle.moodle.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MOD" maxOccurs="unbounded"/>
 *         &lt;element ref="{}METACOURSE"/>
 *         &lt;element ref="{}USERS"/>
 *         &lt;element ref="{}LOGS"/>
 *         &lt;element ref="{}USERFILES"/>
 *         &lt;element ref="{}COURSEFILES"/>
 *         &lt;element ref="{}SITEFILES"/>
 *         &lt;element ref="{}GRADEBOOKHISTORIES"/>
 *         &lt;element ref="{}MESSAGES"/>
 *         &lt;element ref="{}BLOGS"/>
 *         &lt;element ref="{}BLOCKFORMAT"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mod",
    "metacourse",
    "users",
    "logs",
    "userfiles",
    "coursefiles",
    "sitefiles",
    "gradebookhistories",
    "messages",
    "blogs",
    "blockformat"
})
@XmlRootElement(name = "DETAILS")
public class DETAILS {

    @XmlElement(name = "MOD", required = true)
    protected List<MOD> mod;
    @XmlElement(name = "METACOURSE")
    protected boolean metacourse;
    @XmlElement(name = "USERS", required = true)
    protected USERS users;
    @XmlElement(name = "LOGS")
    protected boolean logs;
    @XmlElement(name = "USERFILES")
    protected boolean userfiles;
    @XmlElement(name = "COURSEFILES")
    protected boolean coursefiles;
    @XmlElement(name = "SITEFILES")
    protected boolean sitefiles;
    @XmlElement(name = "GRADEBOOKHISTORIES")
    protected boolean gradebookhistories;
    @XmlElement(name = "MESSAGES")
    protected boolean messages;
    @XmlElement(name = "BLOGS")
    protected boolean blogs;
    @XmlElement(name = "BLOCKFORMAT", required = true)
    protected BLOCKFORMAT blockformat;

    /**
     * Gets the value of the mod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMOD().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MOD }
     * 
     * 
     */
    public List<MOD> getMOD() {
        if (mod == null) {
            mod = new ArrayList<MOD>();
        }
        return this.mod;
    }
    //Para rellenar la lista de modulos
    public void setMODList(List<MOD> moduList){
    	mod=moduList;    	
    }
    
    /**
     * Gets the value of the metacourse property.
     * 
     */
    public boolean isMETACOURSE() {
        return metacourse;
    }

    /**
     * Sets the value of the metacourse property.
     * 
     */
    public void setMETACOURSE(boolean value) {
        this.metacourse = value;
    }

    /**
     * Gets the value of the users property.
     * 
     * @return
     *     possible object is
     *     {@link USERS }
     *     
     */
    public USERS getUSERS() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     * @param value
     *     allowed object is
     *     {@link USERS }
     *     
     */
    public void setUSERS(USERS value) {
        this.users = value;
    }

    /**
     * Gets the value of the logs property.
     * 
     */
    public boolean isLOGS() {
        return logs;
    }

    /**
     * Sets the value of the logs property.
     * 
     */
    public void setLOGS(boolean value) {
        this.logs = value;
    }

    /**
     * Gets the value of the userfiles property.
     * 
     */
    public boolean isUSERFILES() {
        return userfiles;
    }

    /**
     * Sets the value of the userfiles property.
     * 
     */
    public void setUSERFILES(boolean value) {
        this.userfiles = value;
    }

    /**
     * Gets the value of the coursefiles property.
     * 
     */
    public boolean isCOURSEFILES() {
        return coursefiles;
    }

    /**
     * Sets the value of the coursefiles property.
     * 
     */
    public void setCOURSEFILES(boolean value) {
        this.coursefiles = value;
    }

    /**
     * Gets the value of the sitefiles property.
     * 
     */
    public boolean isSITEFILES() {
        return sitefiles;
    }

    /**
     * Sets the value of the sitefiles property.
     * 
     */
    public void setSITEFILES(boolean value) {
        this.sitefiles = value;
    }

    /**
     * Gets the value of the gradebookhistories property.
     * 
     */
    public boolean isGRADEBOOKHISTORIES() {
        return gradebookhistories;
    }

    /**
     * Sets the value of the gradebookhistories property.
     * 
     */
    public void setGRADEBOOKHISTORIES(boolean value) {
        this.gradebookhistories = value;
    }

    /**
     * Gets the value of the messages property.
     * 
     */
    public boolean isMESSAGES() {
        return messages;
    }

    /**
     * Sets the value of the messages property.
     * 
     */
    public void setMESSAGES(boolean value) {
        this.messages = value;
    }

    /**
     * Gets the value of the blogs property.
     * 
     */
    public boolean isBLOGS() {
        return blogs;
    }

    /**
     * Sets the value of the blogs property.
     * 
     */
    public void setBLOGS(boolean value) {
        this.blogs = value;
    }

    /**
     * Gets the value of the blockformat property.
     * 
     * @return
     *     possible object is
     *     {@link BLOCKFORMAT }
     *     
     */
    public BLOCKFORMAT getBLOCKFORMAT() {
        return blockformat;
    }

    /**
     * Sets the value of the blockformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BLOCKFORMAT }
     *     
     */
    public void setBLOCKFORMAT(BLOCKFORMAT value) {
        this.blockformat = value;
    }

}
