//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 04:14:55 PM CEST 
//


package glueps.adaptors.vle.moodle.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ID"/>
 *         &lt;element ref="{}NAME"/>
 *         &lt;element ref="{}DESCRIPTION"/>
 *         &lt;element ref="{}ENROLMENTKEY"/>
 *         &lt;element ref="{}PICTURE"/>
 *         &lt;element ref="{}HIDEPICTURE"/>
 *         &lt;element ref="{}TIMECREATED"/>
 *         &lt;element ref="{}TIMEMODIFIED"/>
 *         &lt;element ref="{}MEMBERS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "name",
    "description",
    "enrolmentkey",
    "picture",
    "hidepicture",
    "timecreated",
    "timemodified",
    "members"
})
@XmlRootElement(name = "GROUP")
public class GROUP implements Cloneable{

    @XmlElement(name = "ID", required = true)
    protected BigInteger id;
    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "DESCRIPTION", required = true)
    protected String description;
    @XmlElement(name = "ENROLMENTKEY", required = true)
    protected ENROLMENTKEY enrolmentkey;
    @XmlElement(name = "PICTURE", required = true)
    protected PICTURE picture;
    @XmlElement(name = "HIDEPICTURE", required = true)
    protected HIDEPICTURE hidepicture;
    @XmlElement(name = "TIMECREATED", required = true)
    protected TIMECREATED timecreated;
    @XmlElement(name = "TIMEMODIFIED", required = true)
    protected TIMEMODIFIED timemodified;
    @XmlElement(name = "MEMBERS", required = true)
    protected MEMBERS members;
    
    
    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the enrolmentkey property.
     * 
     * @return
     *     possible object is
     *     {@link ENROLMENTKEY }
     *     
     */
    public ENROLMENTKEY getENROLMENTKEY() {
        return enrolmentkey;
    }

    /**
     * Sets the value of the enrolmentkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link ENROLMENTKEY }
     *     
     */
    public void setENROLMENTKEY(ENROLMENTKEY value) {
        this.enrolmentkey = value;
    }

    /**
     * Gets the value of the picture property.
     * 
     * @return
     *     possible object is
     *     {@link PICTURE }
     *     
     */
    public PICTURE getPICTURE() {
        return picture;
    }

    /**
     * Sets the value of the picture property.
     * 
     * @param value
     *     allowed object is
     *     {@link PICTURE }
     *     
     */
    public void setPICTURE(PICTURE value) {
        this.picture = value;
    }

    /**
     * Gets the value of the hidepicture property.
     * 
     * @return
     *     possible object is
     *     {@link HIDEPICTURE }
     *     
     */
    public HIDEPICTURE getHIDEPICTURE() {
        return hidepicture;
    }

    /**
     * Sets the value of the hidepicture property.
     * 
     * @param value
     *     allowed object is
     *     {@link HIDEPICTURE }
     *     
     */
    public void setHIDEPICTURE(HIDEPICTURE value) {
        this.hidepicture = value;
    }

    /**
     * Gets the value of the timecreated property.
     * 
     * @return
     *     possible object is
     *     {@link TIMECREATED }
     *     
     */
    public TIMECREATED getTIMECREATED() {
        return timecreated;
    }

    /**
     * Sets the value of the timecreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIMECREATED }
     *     
     */
    public void setTIMECREATED(TIMECREATED value) {
        this.timecreated = value;
    }

    /**
     * Gets the value of the timemodified property.
     * 
     * @return
     *     possible object is
     *     {@link TIMEMODIFIED }
     *     
     */
    public TIMEMODIFIED getTIMEMODIFIED() {
        return timemodified;
    }

    /**
     * Sets the value of the timemodified property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIMEMODIFIED }
     *     
     */
    public void setTIMEMODIFIED(TIMEMODIFIED value) {
        this.timemodified = value;
    }

    /**
     * Gets the value of the members property.
     * 
     * @return
     *     possible object is
     *     {@link MEMBERS }
     *     
     */
    public MEMBERS getMEMBERS() {
        return members;
    }

    /**
     * Sets the value of the members property.
     * 
     * @param value
     *     allowed object is
     *     {@link MEMBERS }
     *     
     */
    public void setMEMBERS(MEMBERS value) {
        this.members = value;
    }
    
    public Object clone() 
    {
        Object clone = null;
         try 
         {
             clone = super.clone();
         }
         catch(CloneNotSupportedException e) 
         {
             // No debería ocurrir
         }
        return clone;
    }

}
