//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 04:14:55 PM CEST 
//


package glueps.adaptors.vle.moodle.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ID"/>
 *         &lt;element ref="{}CATEGORY"/>
 *         &lt;element ref="{}PASSWORD"/>
 *         &lt;element ref="{}FULLNAME"/>
 *         &lt;element ref="{}SHORTNAME"/>
 *         &lt;element ref="{}IDNUMBER"/>
 *         &lt;element ref="{}SUMMARY"/>
 *         &lt;element ref="{}FORMAT"/>
 *         &lt;element ref="{}SHOWGRADES"/>
 *         &lt;element ref="{}NEWSITEMS"/>
 *         &lt;element ref="{}TEACHER"/>
 *         &lt;element ref="{}TEACHERS"/>
 *         &lt;element ref="{}STUDENT"/>
 *         &lt;element ref="{}STUDENTS"/>
 *         &lt;element ref="{}GUEST"/>
 *         &lt;element ref="{}STARTDATE"/>
 *         &lt;element ref="{}NUMSECTIONS"/>
 *         &lt;element ref="{}MAXBYTES"/>
 *         &lt;element ref="{}SHOWREPORTS"/>
 *         &lt;element ref="{}GROUPMODE"/>
 *         &lt;element ref="{}GROUPMODEFORCE"/>
 *         &lt;element ref="{}DEFAULTGROUPINGID"/>
 *         &lt;element ref="{}LANG"/>
 *         &lt;element ref="{}THEME"/>
 *         &lt;element ref="{}COST"/>
 *         &lt;element ref="{}CURRENCY"/>
 *         &lt;element ref="{}MARKER"/>
 *         &lt;element ref="{}VISIBLE"/>
 *         &lt;element ref="{}HIDDENSECTIONS"/>
 *         &lt;element ref="{}TIMECREATED"/>
 *         &lt;element ref="{}TIMEMODIFIED"/>
 *         &lt;element ref="{}METACOURSE"/>
 *         &lt;element ref="{}EXPIRENOTIFY"/>
 *         &lt;element ref="{}NOTIFYSTUDENTS"/>
 *         &lt;element ref="{}EXPIRYTHRESHOLD"/>
 *         &lt;element ref="{}ENROLLABLE"/>
 *         &lt;element ref="{}ENROLSTARTDATE"/>
 *         &lt;element ref="{}ENROLENDDATE"/>
 *         &lt;element ref="{}ENROLPERIOD"/>
 *         &lt;element ref="{}ROLES_OVERRIDES"/>
 *         &lt;element ref="{}ROLES_ASSIGNMENTS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "category",
    "password",
    "fullname",
    "shortname",
    "idnumber",
    "summary",
    "format",
    "showgrades",
    "newsitems",
    "teacher",
    "teachers",
    "student",
    "students",
    "guest",
    "startdate",
    "numsections",
    "maxbytes",
    "showreports",
    "groupmode",
    "groupmodeforce",
    "defaultgroupingid",
    "lang",
    "theme",
    "cost",
    "currency",
    "marker",
    "visible",
    "hiddensections",
    "timecreated",
    "timemodified",
    "metacourse",
    "expirenotify",
    "notifystudents",
    "expirythreshold",
    "enrollable",
    "enrolstartdate",
    "enrolenddate",
    "enrolperiod",
    "rolesoverrides",
    "rolesassignments"
})
@XmlRootElement(name = "HEADER")
public class HEADER {

    @XmlElement(name = "ID", required = true)
    protected BigInteger id;
    @XmlElement(name = "CATEGORY", required = true)
    protected CATEGORY category;
    @XmlElement(name = "PASSWORD", required = true)
    protected PASSWORD password;
    @XmlElement(name = "FULLNAME", required = true)
    protected String fullname;
    @XmlElement(name = "SHORTNAME", required = true)
    protected String shortname;
    @XmlElement(name = "IDNUMBER", required = true)
    protected String idnumber;
    @XmlElement(name = "SUMMARY", required = true)
    protected String summary;
    @XmlElement(name = "FORMAT", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String format;
    @XmlElement(name = "SHOWGRADES", required = true)
    protected BigInteger showgrades;
    @XmlElement(name = "NEWSITEMS", required = true)
    protected BigInteger newsitems;
    @XmlElement(name = "TEACHER", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String teacher;
    @XmlElement(name = "TEACHERS", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String teachers;
    @XmlElement(name = "STUDENT", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String student;
    @XmlElement(name = "STUDENTS", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String students;
    @XmlElement(name = "GUEST", required = true)
    protected BigInteger guest;
    @XmlElement(name = "STARTDATE", required = true)
    protected BigInteger startdate;
    @XmlElement(name = "NUMSECTIONS", required = true)
    protected BigInteger numsections;
    @XmlElement(name = "MAXBYTES", required = true)
    protected BigInteger maxbytes;
    @XmlElement(name = "SHOWREPORTS", required = true)
    protected BigInteger showreports;
    @XmlElement(name = "GROUPMODE", required = true)
    protected BigInteger groupmode;
    @XmlElement(name = "GROUPMODEFORCE", required = true)
    protected BigInteger groupmodeforce;
    @XmlElement(name = "DEFAULTGROUPINGID", required = true)
    protected BigInteger defaultgroupingid;
    @XmlElement(name = "LANG", required = true)
    protected LANG lang;
    @XmlElement(name = "THEME", required = true)
    protected THEME theme;
    @XmlElement(name = "COST", required = true)
    protected COST cost;
    @XmlElement(name = "CURRENCY", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String currency;
    @XmlElement(name = "MARKER", required = true)
    protected BigInteger marker;
    @XmlElement(name = "VISIBLE", required = true)
    protected BigInteger visible;
    @XmlElement(name = "HIDDENSECTIONS", required = true)
    protected BigInteger hiddensections;
    @XmlElement(name = "TIMECREATED", required = true)
    protected TIMECREATED timecreated;
    @XmlElement(name = "TIMEMODIFIED", required = true)
    protected TIMEMODIFIED timemodified;
    @XmlElement(name = "METACOURSE")
    protected boolean metacourse;
    @XmlElement(name = "EXPIRENOTIFY", required = true)
    protected BigInteger expirenotify;
    @XmlElement(name = "NOTIFYSTUDENTS", required = true)
    protected BigInteger notifystudents;
    @XmlElement(name = "EXPIRYTHRESHOLD", required = true)
    protected BigInteger expirythreshold;
    @XmlElement(name = "ENROLLABLE", required = true)
    protected BigInteger enrollable;
    @XmlElement(name = "ENROLSTARTDATE", required = true)
    protected BigInteger enrolstartdate;
    @XmlElement(name = "ENROLENDDATE", required = true)
    protected BigInteger enrolenddate;
    @XmlElement(name = "ENROLPERIOD", required = true)
    protected BigInteger enrolperiod;
    @XmlElement(name = "ROLES_OVERRIDES", required = true)
    protected ROLESOVERRIDES rolesoverrides;
    @XmlElement(name = "ROLES_ASSIGNMENTS", required = true)
    protected ROLESASSIGNMENTS rolesassignments;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link CATEGORY }
     *     
     */
    public CATEGORY getCATEGORY() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link CATEGORY }
     *     
     */
    public void setCATEGORY(CATEGORY value) {
        this.category = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link PASSWORD }
     *     
     */
    public PASSWORD getPASSWORD() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link PASSWORD }
     *     
     */
    public void setPASSWORD(PASSWORD value) {
        this.password = value;
    }

    /**
     * Gets the value of the fullname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFULLNAME() {
        return fullname;
    }

    /**
     * Sets the value of the fullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFULLNAME(String value) {
        this.fullname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHORTNAME() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHORTNAME(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the idnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDNUMBER() {
        return idnumber;
    }

    /**
     * Sets the value of the idnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDNUMBER(String value) {
        this.idnumber = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUMMARY() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUMMARY(String value) {
        this.summary = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFORMAT() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFORMAT(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the showgrades property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSHOWGRADES() {
        return showgrades;
    }

    /**
     * Sets the value of the showgrades property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSHOWGRADES(BigInteger value) {
        this.showgrades = value;
    }

    /**
     * Gets the value of the newsitems property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNEWSITEMS() {
        return newsitems;
    }

    /**
     * Sets the value of the newsitems property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNEWSITEMS(BigInteger value) {
        this.newsitems = value;
    }

    /**
     * Gets the value of the teacher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEACHER() {
        return teacher;
    }

    /**
     * Sets the value of the teacher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEACHER(String value) {
        this.teacher = value;
    }

    /**
     * Gets the value of the teachers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEACHERS() {
        return teachers;
    }

    /**
     * Sets the value of the teachers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEACHERS(String value) {
        this.teachers = value;
    }

    /**
     * Gets the value of the student property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTUDENT() {
        return student;
    }

    /**
     * Sets the value of the student property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTUDENT(String value) {
        this.student = value;
    }

    /**
     * Gets the value of the students property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTUDENTS() {
        return students;
    }

    /**
     * Sets the value of the students property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTUDENTS(String value) {
        this.students = value;
    }

    /**
     * Gets the value of the guest property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGUEST() {
        return guest;
    }

    /**
     * Sets the value of the guest property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGUEST(BigInteger value) {
        this.guest = value;
    }

    /**
     * Gets the value of the startdate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTARTDATE() {
        return startdate;
    }

    /**
     * Sets the value of the startdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTARTDATE(BigInteger value) {
        this.startdate = value;
    }

    /**
     * Gets the value of the numsections property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNUMSECTIONS() {
        return numsections;
    }

    /**
     * Sets the value of the numsections property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNUMSECTIONS(BigInteger value) {
        this.numsections = value;
    }

    /**
     * Gets the value of the maxbytes property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMAXBYTES() {
        return maxbytes;
    }

    /**
     * Sets the value of the maxbytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMAXBYTES(BigInteger value) {
        this.maxbytes = value;
    }

    /**
     * Gets the value of the showreports property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSHOWREPORTS() {
        return showreports;
    }

    /**
     * Sets the value of the showreports property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSHOWREPORTS(BigInteger value) {
        this.showreports = value;
    }

    /**
     * Gets the value of the groupmode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGROUPMODE() {
        return groupmode;
    }

    /**
     * Sets the value of the groupmode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGROUPMODE(BigInteger value) {
        this.groupmode = value;
    }

    /**
     * Gets the value of the groupmodeforce property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGROUPMODEFORCE() {
        return groupmodeforce;
    }

    /**
     * Sets the value of the groupmodeforce property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGROUPMODEFORCE(BigInteger value) {
        this.groupmodeforce = value;
    }

    /**
     * Gets the value of the defaultgroupingid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDEFAULTGROUPINGID() {
        return defaultgroupingid;
    }

    /**
     * Sets the value of the defaultgroupingid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDEFAULTGROUPINGID(BigInteger value) {
        this.defaultgroupingid = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link LANG }
     *     
     */
    public LANG getLANG() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link LANG }
     *     
     */
    public void setLANG(LANG value) {
        this.lang = value;
    }

    /**
     * Gets the value of the theme property.
     * 
     * @return
     *     possible object is
     *     {@link THEME }
     *     
     */
    public THEME getTHEME() {
        return theme;
    }

    /**
     * Sets the value of the theme property.
     * 
     * @param value
     *     allowed object is
     *     {@link THEME }
     *     
     */
    public void setTHEME(THEME value) {
        this.theme = value;
    }

    /**
     * Gets the value of the cost property.
     * 
     * @return
     *     possible object is
     *     {@link COST }
     *     
     */
    public COST getCOST() {
        return cost;
    }

    /**
     * Sets the value of the cost property.
     * 
     * @param value
     *     allowed object is
     *     {@link COST }
     *     
     */
    public void setCOST(COST value) {
        this.cost = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCURRENCY() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCURRENCY(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the marker property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMARKER() {
        return marker;
    }

    /**
     * Sets the value of the marker property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMARKER(BigInteger value) {
        this.marker = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVISIBLE() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVISIBLE(BigInteger value) {
        this.visible = value;
    }

    /**
     * Gets the value of the hiddensections property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHIDDENSECTIONS() {
        return hiddensections;
    }

    /**
     * Sets the value of the hiddensections property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHIDDENSECTIONS(BigInteger value) {
        this.hiddensections = value;
    }

    /**
     * Gets the value of the timecreated property.
     * 
     * @return
     *     possible object is
     *     {@link TIMECREATED }
     *     
     */
    public TIMECREATED getTIMECREATED() {
        return timecreated;
    }

    /**
     * Sets the value of the timecreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIMECREATED }
     *     
     */
    public void setTIMECREATED(TIMECREATED value) {
        this.timecreated = value;
    }

    /**
     * Gets the value of the timemodified property.
     * 
     * @return
     *     possible object is
     *     {@link TIMEMODIFIED }
     *     
     */
    public TIMEMODIFIED getTIMEMODIFIED() {
        return timemodified;
    }

    /**
     * Sets the value of the timemodified property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIMEMODIFIED }
     *     
     */
    public void setTIMEMODIFIED(TIMEMODIFIED value) {
        this.timemodified = value;
    }

    /**
     * Gets the value of the metacourse property.
     * 
     */
    public boolean isMETACOURSE() {
        return metacourse;
    }

    /**
     * Sets the value of the metacourse property.
     * 
     */
    public void setMETACOURSE(boolean value) {
        this.metacourse = value;
    }

    /**
     * Gets the value of the expirenotify property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEXPIRENOTIFY() {
        return expirenotify;
    }

    /**
     * Sets the value of the expirenotify property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEXPIRENOTIFY(BigInteger value) {
        this.expirenotify = value;
    }

    /**
     * Gets the value of the notifystudents property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNOTIFYSTUDENTS() {
        return notifystudents;
    }

    /**
     * Sets the value of the notifystudents property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNOTIFYSTUDENTS(BigInteger value) {
        this.notifystudents = value;
    }

    /**
     * Gets the value of the expirythreshold property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEXPIRYTHRESHOLD() {
        return expirythreshold;
    }

    /**
     * Sets the value of the expirythreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEXPIRYTHRESHOLD(BigInteger value) {
        this.expirythreshold = value;
    }

    /**
     * Gets the value of the enrollable property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getENROLLABLE() {
        return enrollable;
    }

    /**
     * Sets the value of the enrollable property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setENROLLABLE(BigInteger value) {
        this.enrollable = value;
    }

    /**
     * Gets the value of the enrolstartdate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getENROLSTARTDATE() {
        return enrolstartdate;
    }

    /**
     * Sets the value of the enrolstartdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setENROLSTARTDATE(BigInteger value) {
        this.enrolstartdate = value;
    }

    /**
     * Gets the value of the enrolenddate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getENROLENDDATE() {
        return enrolenddate;
    }

    /**
     * Sets the value of the enrolenddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setENROLENDDATE(BigInteger value) {
        this.enrolenddate = value;
    }

    /**
     * Gets the value of the enrolperiod property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getENROLPERIOD() {
        return enrolperiod;
    }

    /**
     * Sets the value of the enrolperiod property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setENROLPERIOD(BigInteger value) {
        this.enrolperiod = value;
    }

    /**
     * Gets the value of the rolesoverrides property.
     * 
     * @return
     *     possible object is
     *     {@link ROLESOVERRIDES }
     *     
     */
    public ROLESOVERRIDES getROLESOVERRIDES() {
        return rolesoverrides;
    }

    /**
     * Sets the value of the rolesoverrides property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROLESOVERRIDES }
     *     
     */
    public void setROLESOVERRIDES(ROLESOVERRIDES value) {
        this.rolesoverrides = value;
    }

    /**
     * Gets the value of the rolesassignments property.
     * 
     * @return
     *     possible object is
     *     {@link ROLESASSIGNMENTS }
     *     
     */
    public ROLESASSIGNMENTS getROLESASSIGNMENTS() {
        return rolesassignments;
    }

    /**
     * Sets the value of the rolesassignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROLESASSIGNMENTS }
     *     
     */
    public void setROLESASSIGNMENTS(ROLESASSIGNMENTS value) {
        this.rolesassignments = value;
    }

}
