//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 04:14:55 PM CEST 
//


package glueps.adaptors.vle.moodle.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NAME"/>
 *         &lt;element ref="{}MOODLE_VERSION"/>
 *         &lt;element ref="{}MOODLE_RELEASE"/>
 *         &lt;element ref="{}BACKUP_VERSION"/>
 *         &lt;element ref="{}BACKUP_RELEASE"/>
 *         &lt;element ref="{}DATE"/>
 *         &lt;element ref="{}ORIGINAL_WWWROOT"/>
 *         &lt;element ref="{}ORIGINAL_SITE_IDENTIFIER_HASH"/>
 *         &lt;element ref="{}ZIP_METHOD"/>
 *         &lt;element ref="{}DETAILS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "moodleversion",
    "moodlerelease",
    "backupversion",
    "backuprelease",
    "date",
    "originalwwwroot",
    "originalsiteidentifierhash",
    "zipmethod",
    "details"
})
@XmlRootElement(name = "INFO")
public class INFO {

    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "MOODLE_VERSION", required = true)
    protected BigDecimal moodleversion;
    @XmlElement(name = "MOODLE_RELEASE", required = true)
    protected String moodlerelease;
    @XmlElement(name = "BACKUP_VERSION", required = true)
    protected BigInteger backupversion;
    @XmlElement(name = "BACKUP_RELEASE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backuprelease;
    @XmlElement(name = "DATE", required = true)
    protected BigInteger date;
    @XmlElement(name = "ORIGINAL_WWWROOT", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String originalwwwroot;
    @XmlElement(name = "ORIGINAL_SITE_IDENTIFIER_HASH", required = true)
    protected String originalsiteidentifierhash;
    @XmlElement(name = "ZIP_METHOD", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String zipmethod;
    @XmlElement(name = "DETAILS", required = true)
    protected DETAILS details;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the moodleversion property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMOODLEVERSION() {
        return moodleversion;
    }

    /**
     * Sets the value of the moodleversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMOODLEVERSION(BigDecimal value) {
        this.moodleversion = value;
    }

    /**
     * Gets the value of the moodlerelease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOODLERELEASE() {
        return moodlerelease;
    }

    /**
     * Sets the value of the moodlerelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOODLERELEASE(String value) {
        this.moodlerelease = value;
    }

    /**
     * Gets the value of the backupversion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBACKUPVERSION() {
        return backupversion;
    }

    /**
     * Sets the value of the backupversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBACKUPVERSION(BigInteger value) {
        this.backupversion = value;
    }

    /**
     * Gets the value of the backuprelease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBACKUPRELEASE() {
        return backuprelease;
    }

    /**
     * Sets the value of the backuprelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBACKUPRELEASE(String value) {
        this.backuprelease = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDATE() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDATE(BigInteger value) {
        this.date = value;
    }

    /**
     * Gets the value of the originalwwwroot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORIGINALWWWROOT() {
        return originalwwwroot;
    }

    /**
     * Sets the value of the originalwwwroot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORIGINALWWWROOT(String value) {
        this.originalwwwroot = value;
    }

    /**
     * Gets the value of the originalsiteidentifierhash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORIGINALSITEIDENTIFIERHASH() {
        return originalsiteidentifierhash;
    }

    /**
     * Sets the value of the originalsiteidentifierhash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORIGINALSITEIDENTIFIERHASH(String value) {
        this.originalsiteidentifierhash = value;
    }

    /**
     * Gets the value of the zipmethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZIPMETHOD() {
        return zipmethod;
    }

    /**
     * Sets the value of the zipmethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZIPMETHOD(String value) {
        this.zipmethod = value;
    }

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link DETAILS }
     *     
     */
    public DETAILS getDETAILS() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link DETAILS }
     *     
     */
    public void setDETAILS(DETAILS value) {
        this.details = value;
    }

}
