//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 04:14:55 PM CEST 
//


package glueps.adaptors.vle.moodle.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ID"/>
 *         &lt;element ref="{}MANIFEST"/>
 *         &lt;element ref="{}ORGANIZATION"/>
 *         &lt;element ref="{}PARENT"/>
 *         &lt;element ref="{}IDENTIFIER"/>
 *         &lt;element ref="{}LAUNCH"/>
 *         &lt;element ref="{}SCORMTYPE"/>
 *         &lt;element ref="{}TITLE"/>
 *         &lt;element ref="{}SCO_DATAS"/>
 *         &lt;element ref="{}SEQ_RULECONDS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "manifest",
    "organization",
    "parent",
    "identifier",
    "launch",
    "scormtype",
    "title",
    "scodatas",
    "seqruleconds"
})
@XmlRootElement(name = "SCO")
public class SCO {

    @XmlElement(name = "ID", required = true)
    protected BigInteger id;
    @XmlElement(name = "MANIFEST", required = true)
    protected String manifest;
    @XmlElement(name = "ORGANIZATION", required = true)
    protected String organization;
    @XmlElement(name = "PARENT", required = true)
    protected String parent;
    @XmlElement(name = "IDENTIFIER", required = true)
    protected String identifier;
    @XmlElement(name = "LAUNCH", required = true)
    protected String launch;
    @XmlElement(name = "SCORMTYPE", required = true)
    protected String scormtype;
    @XmlElement(name = "TITLE", required = true)
    protected String title;
    @XmlElement(name = "SCO_DATAS", required = true)
    protected SCODATAS scodatas;
    @XmlElement(name = "SEQ_RULECONDS")
    protected SEQRULECONDS seqruleconds;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the manifest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMANIFEST() {
        return manifest;
    }

    /**
     * Sets the value of the manifest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMANIFEST(String value) {
        this.manifest = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORGANIZATION() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORGANIZATION(String value) {
        this.organization = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARENT() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARENT(String value) {
        this.parent = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDENTIFIER() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDENTIFIER(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the launch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLAUNCH() {
        return launch;
    }

    /**
     * Sets the value of the launch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLAUNCH(String value) {
        this.launch = value;
    }

    /**
     * Gets the value of the scormtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCORMTYPE() {
        return scormtype;
    }

    /**
     * Sets the value of the scormtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCORMTYPE(String value) {
        this.scormtype = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTITLE() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTITLE(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the scodatas property.
     * 
     * @return
     *     possible object is
     *     {@link SCODATAS }
     *     
     */
    public SCODATAS getSCODATAS() {
        return scodatas;
    }

    /**
     * Sets the value of the scodatas property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCODATAS }
     *     
     */
    public void setSCODATAS(SCODATAS value) {
        this.scodatas = value;
    }

    /**
     * Gets the value of the seqruleconds property.
     * 
     * @return
     *     possible object is
     *     {@link SEQRULECONDS }
     *     
     */
    public SEQRULECONDS getSEQRULECONDS() {
        return seqruleconds;
    }

    /**
     * Sets the value of the seqruleconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link SEQRULECONDS }
     *     
     */
    public void setSEQRULECONDS(SEQRULECONDS value) {
        this.seqruleconds = value;
    }

}
