/*******************************************************************************
 * Copyright (C) 2015 Intelligent & Cooperative Systems Research Group/Education,
 * Media, Computing & Culture (GSIC-EMIC). University of Valladolid(UVA). 
 * Valladolid, Spain. https://www.gsic.uva.es/
 * 
 * This file is part of Glue!PS.
 * 
 * Glue!PS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version.
 * 
 * Glue!PS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 04:14:55 PM CEST 
//


package glueps.adaptors.vle.moodle.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ID"/>
 *         &lt;element ref="{}SCOID"/>
 *         &lt;element ref="{}CONDITIONCOMBINATION"/>
 *         &lt;element ref="{}RULETYPE"/>
 *         &lt;element ref="{}ACTION"/>
 *         &lt;element ref="{}SEQ_RULECOND_DATAS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "scoid",
    "conditioncombination",
    "ruletype",
    "action",
    "seqruleconddatas"
})
@XmlRootElement(name = "SEQ_RULECOND")
public class SEQRULECOND {

    @XmlElement(name = "ID", required = true)
    protected BigInteger id;
    @XmlElement(name = "SCOID", required = true)
    protected BigInteger scoid;
    @XmlElement(name = "CONDITIONCOMBINATION", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String conditioncombination;
    @XmlElement(name = "RULETYPE", required = true)
    protected BigInteger ruletype;
    @XmlElement(name = "ACTION", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String action;
    @XmlElement(name = "SEQ_RULECOND_DATAS", required = true)
    protected SEQRULECONDDATAS seqruleconddatas;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the scoid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSCOID() {
        return scoid;
    }

    /**
     * Sets the value of the scoid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSCOID(BigInteger value) {
        this.scoid = value;
    }

    /**
     * Gets the value of the conditioncombination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONDITIONCOMBINATION() {
        return conditioncombination;
    }

    /**
     * Sets the value of the conditioncombination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONDITIONCOMBINATION(String value) {
        this.conditioncombination = value;
    }

    /**
     * Gets the value of the ruletype property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRULETYPE() {
        return ruletype;
    }

    /**
     * Sets the value of the ruletype property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRULETYPE(BigInteger value) {
        this.ruletype = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTION() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTION(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the seqruleconddatas property.
     * 
     * @return
     *     possible object is
     *     {@link SEQRULECONDDATAS }
     *     
     */
    public SEQRULECONDDATAS getSEQRULECONDDATAS() {
        return seqruleconddatas;
    }

    /**
     * Sets the value of the seqruleconddatas property.
     * 
     * @param value
     *     allowed object is
     *     {@link SEQRULECONDDATAS }
     *     
     */
    public void setSEQRULECONDDATAS(SEQRULECONDDATAS value) {
        this.seqruleconddatas = value;
    }

}
