//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 04:14:55 PM CEST 
//


package glueps.adaptors.vle.moodle.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SEQ_RULECOND_DATA"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "seqruleconddata"
})
@XmlRootElement(name = "SEQ_RULECOND_DATAS")
public class SEQRULECONDDATAS {

    @XmlElement(name = "SEQ_RULECOND_DATA", required = true)
    protected SEQRULECONDDATA seqruleconddata;

    /**
     * Gets the value of the seqruleconddata property.
     * 
     * @return
     *     possible object is
     *     {@link SEQRULECONDDATA }
     *     
     */
    public SEQRULECONDDATA getSEQRULECONDDATA() {
        return seqruleconddata;
    }

    /**
     * Sets the value of the seqruleconddata property.
     * 
     * @param value
     *     allowed object is
     *     {@link SEQRULECONDDATA }
     *     
     */
    public void setSEQRULECONDDATA(SEQRULECONDDATA value) {
        this.seqruleconddata = value;
    }

}
