//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 04:14:55 PM CEST 
//


package glueps.adaptors.vle.moodle.model;

import java.math.BigInteger;
import java.util.Vector;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ID"/>
 *         &lt;element ref="{}AUTH"/>
 *         &lt;element ref="{}CONFIRMED"/>
 *         &lt;element ref="{}POLICYAGREED"/>
 *         &lt;element ref="{}DELETED"/>
 *         &lt;element ref="{}USERNAME"/>
 *         &lt;element ref="{}IDNUMBER"/>
 *         &lt;element ref="{}FIRSTNAME"/>
 *         &lt;element ref="{}LASTNAME"/>
 *         &lt;element ref="{}EMAIL"/>
 *         &lt;element ref="{}EMAILSTOP"/>
 *         &lt;element ref="{}ICQ"/>
 *         &lt;element ref="{}SKYPE"/>
 *         &lt;element ref="{}YAHOO"/>
 *         &lt;element ref="{}AIM"/>
 *         &lt;element ref="{}MSN"/>
 *         &lt;element ref="{}PHONE1"/>
 *         &lt;element ref="{}PHONE2"/>
 *         &lt;element ref="{}INSTITUTION"/>
 *         &lt;element ref="{}DEPARTMENT"/>
 *         &lt;element ref="{}ADDRESS"/>
 *         &lt;element ref="{}CITY"/>
 *         &lt;element ref="{}COUNTRY"/>
 *         &lt;element ref="{}LANG"/>
 *         &lt;element ref="{}THEME"/>
 *         &lt;element ref="{}TIMEZONE"/>
 *         &lt;element ref="{}FIRSTACCESS"/>
 *         &lt;element ref="{}LASTACCESS"/>
 *         &lt;element ref="{}LASTLOGIN"/>
 *         &lt;element ref="{}CURRENTLOGIN"/>
 *         &lt;element ref="{}LASTIP"/>
 *         &lt;element ref="{}PICTURE"/>
 *         &lt;element ref="{}URL"/>
 *         &lt;element ref="{}DESCRIPTION"/>
 *         &lt;element ref="{}MAILFORMAT"/>
 *         &lt;element ref="{}MAILDIGEST"/>
 *         &lt;element ref="{}MAILDISPLAY"/>
 *         &lt;element ref="{}HTMLEDITOR"/>
 *         &lt;element ref="{}AJAX"/>
 *         &lt;element ref="{}AUTOSUBSCRIBE"/>
 *         &lt;element ref="{}TRACKFORUMS"/>
 *         &lt;element ref="{}TIMEMODIFIED"/>
 *         &lt;element ref="{}ROLES"/>
 *         &lt;element ref="{}USER_PREFERENCES"/>
 *         &lt;element ref="{}ROLES_OVERRIDES"/>
 *         &lt;element ref="{}ROLES_ASSIGNMENTS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "auth",
    "confirmed",
    "policyagreed",
    "deleted",
    "username",
    "idnumber",
    "firstname",
    "lastname",
    "email",
    "emailstop",
    "icq",
    "skype",
    "yahoo",
    "aim",
    "msn",
    "phone1",
    "phone2",
    "institution",
    "department",
    "address",
    "city",
    "country",
    "lang",
    "theme",
    "timezone",
    "firstaccess",
    "lastaccess",
    "lastlogin",
    "currentlogin",
    "lastip",
    "picture",
    "url",
    "description",
    "mailformat",
    "maildigest",
    "maildisplay",
    "htmleditor",
    "ajax",
    "autosubscribe",
    "trackforums",
    "timemodified",
    "roles",
    "userpreferences",
    "rolesoverrides",
    "rolesassignments"
})
@XmlRootElement(name = "USER")
public class USER  implements Cloneable{

    @XmlElement(name = "ID", required = true)
    protected BigInteger id;
    @XmlElement(name = "AUTH", required = true)
    protected AUTH auth;
    @XmlElement(name = "CONFIRMED", required = true)
    protected CONFIRMED confirmed;
    @XmlElement(name = "POLICYAGREED", required = true)
    protected POLICYAGREED policyagreed;
    @XmlElement(name = "DELETED", required = true)
    protected DELETED deleted;
    @XmlElement(name = "USERNAME", required = true)
    protected String username;
    @XmlElement(name = "IDNUMBER", required = true)
    protected String idnumber;
    @XmlElement(name = "FIRSTNAME", required = true)
    protected FIRSTNAME firstname;
    @XmlElement(name = "LASTNAME", required = true)
    protected LASTNAME lastname;
    @XmlElement(name = "EMAIL", required = true)
    protected String email;
    @XmlElement(name = "EMAILSTOP", required = true)
    protected EMAILSTOP emailstop;
    @XmlElement(name = "ICQ", required = true)
    protected ICQ icq;
    @XmlElement(name = "SKYPE", required = true)
    protected SKYPE skype;
    @XmlElement(name = "YAHOO", required = true)
    protected YAHOO yahoo;
    @XmlElement(name = "AIM", required = true)
    protected AIM aim;
    @XmlElement(name = "MSN", required = true)
    protected MSN msn;
    @XmlElement(name = "PHONE1", required = true)
    protected PHONE1 phone1;
    @XmlElement(name = "PHONE2", required = true)
    protected PHONE2 phone2;
    @XmlElement(name = "INSTITUTION", required = true)
    protected INSTITUTION institution;
    @XmlElement(name = "DEPARTMENT", required = true)
    protected DEPARTMENT department;
    @XmlElement(name = "ADDRESS", required = true)
    protected ADDRESS address;
    @XmlElement(name = "CITY", required = true)
    protected CITY city;
    @XmlElement(name = "COUNTRY", required = true)
    protected COUNTRY country;
    @XmlElement(name = "LANG", required = true)
    protected LANG lang;
    @XmlElement(name = "THEME", required = true)
    protected THEME theme;
    @XmlElement(name = "TIMEZONE", required = true)
    protected TIMEZONE timezone;
    @XmlElement(name = "FIRSTACCESS", required = true)
    protected BigInteger firstaccess;
    @XmlElement(name = "LASTACCESS", required = true)
    protected LASTACCESS lastaccess;
    @XmlElement(name = "LASTLOGIN", required = true)
    protected LASTLOGIN lastlogin;
    @XmlElement(name = "CURRENTLOGIN", required = true)
    protected CURRENTLOGIN currentlogin;
    @XmlElement(name = "LASTIP", required = true)
    protected LASTIP lastip;
    @XmlElement(name = "PICTURE", required = true)
    protected PICTURE picture;
    @XmlElement(name = "URL", required = true)
    protected URL url;
    @XmlElement(name = "DESCRIPTION", required = true)
    protected String description;
    @XmlElement(name = "MAILFORMAT", required = true)
    protected MAILFORMAT mailformat;
    @XmlElement(name = "MAILDIGEST", required = true)
    protected MAILDIGEST maildigest;
    @XmlElement(name = "MAILDISPLAY", required = true)
    protected MAILDISPLAY maildisplay;
    @XmlElement(name = "HTMLEDITOR", required = true)
    protected HTMLEDITOR htmleditor;
    @XmlElement(name = "AJAX", required = true)
    protected AJAX ajax;
    @XmlElement(name = "AUTOSUBSCRIBE", required = true)
    protected AUTOSUBSCRIBE autosubscribe;
    @XmlElement(name = "TRACKFORUMS", required = true)
    protected TRACKFORUMS trackforums;
    @XmlElement(name = "TIMEMODIFIED", required = true)
    protected TIMEMODIFIED timemodified;
    @XmlElement(name = "ROLES", required = true)
    protected ROLES roles;
    @XmlElement(name = "USER_PREFERENCES", required = true)
    protected USERPREFERENCES userpreferences;
    @XmlElement(name = "ROLES_OVERRIDES", required = true)
    protected ROLESOVERRIDES rolesoverrides;
    @XmlElement(name = "ROLES_ASSIGNMENTS", required = true)
    protected ROLESASSIGNMENTS rolesassignments;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the auth property.
     * 
     * @return
     *     possible object is
     *     {@link AUTH }
     *     
     */
    public AUTH getAUTH() {
        return auth;
    }

    /**
     * Sets the value of the auth property.
     * 
     * @param value
     *     allowed object is
     *     {@link AUTH }
     *     
     */
    public void setAUTH(AUTH value) {
        this.auth = value;
    }

    /**
     * Gets the value of the confirmed property.
     * 
     * @return
     *     possible object is
     *     {@link CONFIRMED }
     *     
     */
    public CONFIRMED getCONFIRMED() {
        return confirmed;
    }

    /**
     * Sets the value of the confirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONFIRMED }
     *     
     */
    public void setCONFIRMED(CONFIRMED value) {
        this.confirmed = value;
    }

    /**
     * Gets the value of the policyagreed property.
     * 
     * @return
     *     possible object is
     *     {@link POLICYAGREED }
     *     
     */
    public POLICYAGREED getPOLICYAGREED() {
        return policyagreed;
    }

    /**
     * Sets the value of the policyagreed property.
     * 
     * @param value
     *     allowed object is
     *     {@link POLICYAGREED }
     *     
     */
    public void setPOLICYAGREED(POLICYAGREED value) {
        this.policyagreed = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     * @return
     *     possible object is
     *     {@link DELETED }
     *     
     */
    public DELETED getDELETED() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link DELETED }
     *     
     */
    public void setDELETED(DELETED value) {
        this.deleted = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERNAME() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERNAME(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the idnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDNUMBER() {
        return idnumber;
    }

    /**
     * Sets the value of the idnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDNUMBER(String value) {
        this.idnumber = value;
    }

    /**
     * Gets the value of the firstname property.
     * 
     * @return
     *     possible object is
     *     {@link FIRSTNAME }
     *     
     */
    public FIRSTNAME getFIRSTNAME() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link FIRSTNAME }
     *     
     */
    public void setFIRSTNAME(FIRSTNAME value) {
        this.firstname = value;
    }

    /**
     * Gets the value of the lastname property.
     * 
     * @return
     *     possible object is
     *     {@link LASTNAME }
     *     
     */
    public LASTNAME getLASTNAME() {
        return lastname;
    }

    /**
     * Sets the value of the lastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link LASTNAME }
     *     
     */
    public void setLASTNAME(LASTNAME value) {
        this.lastname = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMAIL() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMAIL(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the emailstop property.
     * 
     * @return
     *     possible object is
     *     {@link EMAILSTOP }
     *     
     */
    public EMAILSTOP getEMAILSTOP() {
        return emailstop;
    }

    /**
     * Sets the value of the emailstop property.
     * 
     * @param value
     *     allowed object is
     *     {@link EMAILSTOP }
     *     
     */
    public void setEMAILSTOP(EMAILSTOP value) {
        this.emailstop = value;
    }

    /**
     * Gets the value of the icq property.
     * 
     * @return
     *     possible object is
     *     {@link ICQ }
     *     
     */
    public ICQ getICQ() {
        return icq;
    }

    /**
     * Sets the value of the icq property.
     * 
     * @param value
     *     allowed object is
     *     {@link ICQ }
     *     
     */
    public void setICQ(ICQ value) {
        this.icq = value;
    }

    /**
     * Gets the value of the skype property.
     * 
     * @return
     *     possible object is
     *     {@link SKYPE }
     *     
     */
    public SKYPE getSKYPE() {
        return skype;
    }

    /**
     * Sets the value of the skype property.
     * 
     * @param value
     *     allowed object is
     *     {@link SKYPE }
     *     
     */
    public void setSKYPE(SKYPE value) {
        this.skype = value;
    }

    /**
     * Gets the value of the yahoo property.
     * 
     * @return
     *     possible object is
     *     {@link YAHOO }
     *     
     */
    public YAHOO getYAHOO() {
        return yahoo;
    }

    /**
     * Sets the value of the yahoo property.
     * 
     * @param value
     *     allowed object is
     *     {@link YAHOO }
     *     
     */
    public void setYAHOO(YAHOO value) {
        this.yahoo = value;
    }

    /**
     * Gets the value of the aim property.
     * 
     * @return
     *     possible object is
     *     {@link AIM }
     *     
     */
    public AIM getAIM() {
        return aim;
    }

    /**
     * Sets the value of the aim property.
     * 
     * @param value
     *     allowed object is
     *     {@link AIM }
     *     
     */
    public void setAIM(AIM value) {
        this.aim = value;
    }

    /**
     * Gets the value of the msn property.
     * 
     * @return
     *     possible object is
     *     {@link MSN }
     *     
     */
    public MSN getMSN() {
        return msn;
    }

    /**
     * Sets the value of the msn property.
     * 
     * @param value
     *     allowed object is
     *     {@link MSN }
     *     
     */
    public void setMSN(MSN value) {
        this.msn = value;
    }

    /**
     * Gets the value of the phone1 property.
     * 
     * @return
     *     possible object is
     *     {@link PHONE1 }
     *     
     */
    public PHONE1 getPHONE1() {
        return phone1;
    }

    /**
     * Sets the value of the phone1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PHONE1 }
     *     
     */
    public void setPHONE1(PHONE1 value) {
        this.phone1 = value;
    }

    /**
     * Gets the value of the phone2 property.
     * 
     * @return
     *     possible object is
     *     {@link PHONE2 }
     *     
     */
    public PHONE2 getPHONE2() {
        return phone2;
    }

    /**
     * Sets the value of the phone2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PHONE2 }
     *     
     */
    public void setPHONE2(PHONE2 value) {
        this.phone2 = value;
    }

    /**
     * Gets the value of the institution property.
     * 
     * @return
     *     possible object is
     *     {@link INSTITUTION }
     *     
     */
    public INSTITUTION getINSTITUTION() {
        return institution;
    }

    /**
     * Sets the value of the institution property.
     * 
     * @param value
     *     allowed object is
     *     {@link INSTITUTION }
     *     
     */
    public void setINSTITUTION(INSTITUTION value) {
        this.institution = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * @return
     *     possible object is
     *     {@link DEPARTMENT }
     *     
     */
    public DEPARTMENT getDEPARTMENT() {
        return department;
    }

    /**
     * Sets the value of the department property.
     * 
     * @param value
     *     allowed object is
     *     {@link DEPARTMENT }
     *     
     */
    public void setDEPARTMENT(DEPARTMENT value) {
        this.department = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link ADDRESS }
     *     
     */
    public ADDRESS getADDRESS() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link ADDRESS }
     *     
     */
    public void setADDRESS(ADDRESS value) {
        this.address = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link CITY }
     *     
     */
    public CITY getCITY() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link CITY }
     *     
     */
    public void setCITY(CITY value) {
        this.city = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link COUNTRY }
     *     
     */
    public COUNTRY getCOUNTRY() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link COUNTRY }
     *     
     */
    public void setCOUNTRY(COUNTRY value) {
        this.country = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link LANG }
     *     
     */
    public LANG getLANG() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link LANG }
     *     
     */
    public void setLANG(LANG value) {
        this.lang = value;
    }

    /**
     * Gets the value of the theme property.
     * 
     * @return
     *     possible object is
     *     {@link THEME }
     *     
     */
    public THEME getTHEME() {
        return theme;
    }

    /**
     * Sets the value of the theme property.
     * 
     * @param value
     *     allowed object is
     *     {@link THEME }
     *     
     */
    public void setTHEME(THEME value) {
        this.theme = value;
    }

    /**
     * Gets the value of the timezone property.
     * 
     * @return
     *     possible object is
     *     {@link TIMEZONE }
     *     
     */
    public TIMEZONE getTIMEZONE() {
        return timezone;
    }

    /**
     * Sets the value of the timezone property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIMEZONE }
     *     
     */
    public void setTIMEZONE(TIMEZONE value) {
        this.timezone = value;
    }

    /**
     * Gets the value of the firstaccess property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFIRSTACCESS() {
        return firstaccess;
    }

    /**
     * Sets the value of the firstaccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFIRSTACCESS(BigInteger value) {
        this.firstaccess = value;
    }

    /**
     * Gets the value of the lastaccess property.
     * 
     * @return
     *     possible object is
     *     {@link LASTACCESS }
     *     
     */
    public LASTACCESS getLASTACCESS() {
        return lastaccess;
    }

    /**
     * Sets the value of the lastaccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link LASTACCESS }
     *     
     */
    public void setLASTACCESS(LASTACCESS value) {
        this.lastaccess = value;
    }

    /**
     * Gets the value of the lastlogin property.
     * 
     * @return
     *     possible object is
     *     {@link LASTLOGIN }
     *     
     */
    public LASTLOGIN getLASTLOGIN() {
        return lastlogin;
    }

    /**
     * Sets the value of the lastlogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link LASTLOGIN }
     *     
     */
    public void setLASTLOGIN(LASTLOGIN value) {
        this.lastlogin = value;
    }

    /**
     * Gets the value of the currentlogin property.
     * 
     * @return
     *     possible object is
     *     {@link CURRENTLOGIN }
     *     
     */
    public CURRENTLOGIN getCURRENTLOGIN() {
        return currentlogin;
    }

    /**
     * Sets the value of the currentlogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURRENTLOGIN }
     *     
     */
    public void setCURRENTLOGIN(CURRENTLOGIN value) {
        this.currentlogin = value;
    }

    /**
     * Gets the value of the lastip property.
     * 
     * @return
     *     possible object is
     *     {@link LASTIP }
     *     
     */
    public LASTIP getLASTIP() {
        return lastip;
    }

    /**
     * Sets the value of the lastip property.
     * 
     * @param value
     *     allowed object is
     *     {@link LASTIP }
     *     
     */
    public void setLASTIP(LASTIP value) {
        this.lastip = value;
    }

    /**
     * Gets the value of the picture property.
     * 
     * @return
     *     possible object is
     *     {@link PICTURE }
     *     
     */
    public PICTURE getPICTURE() {
        return picture;
    }

    /**
     * Sets the value of the picture property.
     * 
     * @param value
     *     allowed object is
     *     {@link PICTURE }
     *     
     */
    public void setPICTURE(PICTURE value) {
        this.picture = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link URL }
     *     
     */
    public URL getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link URL }
     *     
     */
    public void setURL(URL value) {
        this.url = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the mailformat property.
     * 
     * @return
     *     possible object is
     *     {@link MAILFORMAT }
     *     
     */
    public MAILFORMAT getMAILFORMAT() {
        return mailformat;
    }

    /**
     * Sets the value of the mailformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link MAILFORMAT }
     *     
     */
    public void setMAILFORMAT(MAILFORMAT value) {
        this.mailformat = value;
    }

    /**
     * Gets the value of the maildigest property.
     * 
     * @return
     *     possible object is
     *     {@link MAILDIGEST }
     *     
     */
    public MAILDIGEST getMAILDIGEST() {
        return maildigest;
    }

    /**
     * Sets the value of the maildigest property.
     * 
     * @param value
     *     allowed object is
     *     {@link MAILDIGEST }
     *     
     */
    public void setMAILDIGEST(MAILDIGEST value) {
        this.maildigest = value;
    }

    /**
     * Gets the value of the maildisplay property.
     * 
     * @return
     *     possible object is
     *     {@link MAILDISPLAY }
     *     
     */
    public MAILDISPLAY getMAILDISPLAY() {
        return maildisplay;
    }

    /**
     * Sets the value of the maildisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link MAILDISPLAY }
     *     
     */
    public void setMAILDISPLAY(MAILDISPLAY value) {
        this.maildisplay = value;
    }

    /**
     * Gets the value of the htmleditor property.
     * 
     * @return
     *     possible object is
     *     {@link HTMLEDITOR }
     *     
     */
    public HTMLEDITOR getHTMLEDITOR() {
        return htmleditor;
    }

    /**
     * Sets the value of the htmleditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link HTMLEDITOR }
     *     
     */
    public void setHTMLEDITOR(HTMLEDITOR value) {
        this.htmleditor = value;
    }

    /**
     * Gets the value of the ajax property.
     * 
     * @return
     *     possible object is
     *     {@link AJAX }
     *     
     */
    public AJAX getAJAX() {
        return ajax;
    }

    /**
     * Sets the value of the ajax property.
     * 
     * @param value
     *     allowed object is
     *     {@link AJAX }
     *     
     */
    public void setAJAX(AJAX value) {
        this.ajax = value;
    }

    /**
     * Gets the value of the autosubscribe property.
     * 
     * @return
     *     possible object is
     *     {@link AUTOSUBSCRIBE }
     *     
     */
    public AUTOSUBSCRIBE getAUTOSUBSCRIBE() {
        return autosubscribe;
    }

    /**
     * Sets the value of the autosubscribe property.
     * 
     * @param value
     *     allowed object is
     *     {@link AUTOSUBSCRIBE }
     *     
     */
    public void setAUTOSUBSCRIBE(AUTOSUBSCRIBE value) {
        this.autosubscribe = value;
    }

    /**
     * Gets the value of the trackforums property.
     * 
     * @return
     *     possible object is
     *     {@link TRACKFORUMS }
     *     
     */
    public TRACKFORUMS getTRACKFORUMS() {
        return trackforums;
    }

    /**
     * Sets the value of the trackforums property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRACKFORUMS }
     *     
     */
    public void setTRACKFORUMS(TRACKFORUMS value) {
        this.trackforums = value;
    }

    /**
     * Gets the value of the timemodified property.
     * 
     * @return
     *     possible object is
     *     {@link TIMEMODIFIED }
     *     
     */
    public TIMEMODIFIED getTIMEMODIFIED() {
        return timemodified;
    }

    /**
     * Sets the value of the timemodified property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIMEMODIFIED }
     *     
     */
    public void setTIMEMODIFIED(TIMEMODIFIED value) {
        this.timemodified = value;
    }

    /**
     * Gets the value of the roles property.
     * 
     * @return
     *     possible object is
     *     {@link ROLES }
     *     
     */
    public ROLES getROLES() {
        return roles;
    }

    /**
     * Sets the value of the roles property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROLES }
     *     
     */
    public void setROLES(ROLES value) {
        this.roles = value;
    }

    /**
     * Gets the value of the userpreferences property.
     * 
     * @return
     *     possible object is
     *     {@link USERPREFERENCES }
     *     
     */
    public USERPREFERENCES getUSERPREFERENCES() {
        return userpreferences;
    }

    /**
     * Sets the value of the userpreferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link USERPREFERENCES }
     *     
     */
    public void setUSERPREFERENCES(USERPREFERENCES value) {
        this.userpreferences = value;
    }

    /**
     * Gets the value of the rolesoverrides property.
     * 
     * @return
     *     possible object is
     *     {@link ROLESOVERRIDES }
     *     
     */
    public ROLESOVERRIDES getROLESOVERRIDES() {
        return rolesoverrides;
    }

    /**
     * Sets the value of the rolesoverrides property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROLESOVERRIDES }
     *     
     */
    public void setROLESOVERRIDES(ROLESOVERRIDES value) {
        this.rolesoverrides = value;
    }

    /**
     * Gets the value of the rolesassignments property.
     * 
     * @return
     *     possible object is
     *     {@link ROLESASSIGNMENTS }
     *     
     */
    public ROLESASSIGNMENTS getROLESASSIGNMENTS() {
        return rolesassignments;
    }

    /**
     * Sets the value of the rolesassignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ROLESASSIGNMENTS }
     *     
     */
    public void setROLESASSIGNMENTS(ROLESASSIGNMENTS value) {
        this.rolesassignments = value;
    }
    public Object clone() 
    {
        Object clone = null;
         try 
         {
             clone = super.clone();
         }
         catch(CloneNotSupportedException e) 
         {
             // No debería ocurrir
         }
        return clone;
    }


}
