//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.06 at 06:20:42 PM CET 
//


package glueps.adaptors.ld.pp.model;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the glueps.adaptors.pp.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PlanUsecase_QNAME = new QName("", "plan_usecase");
    private final static QName _PlanTagAttributeTitle_QNAME = new QName("", "plan_tag_attribute_title");
    private final static QName _PlanActivityOpzattv_QNAME = new QName("", "plan_activity_opzattv");
    private final static QName _PlanAuthor_QNAME = new QName("", "plan_author");
    private final static QName _PlanTagAttributeValue_QNAME = new QName("", "plan_tag_attribute_value");
    private final static QName _PlanAttributeName_QNAME = new QName("", "plan_attribute_name");
    private final static QName _PlanDescription_QNAME = new QName("", "plan_description");
    private final static QName _PlanTitle_QNAME = new QName("", "plan_title");
    private final static QName _PlanActivityFieldName_QNAME = new QName("", "plan_activity_field_name");
    private final static QName _PlanEmail_QNAME = new QName("", "plan_email");
    private final static QName _PlanTagValue_QNAME = new QName("", "plan_tag_value");
    private final static QName _PlanActivityOrder_QNAME = new QName("", "plan_activity_order");
    private final static QName _PlanTagAttributeCode_QNAME = new QName("", "plan_tag_attribute_code");
    private final static QName _PlanActivityResourceLink_QNAME = new QName("", "plan_activity_resource_link");
    private final static QName _PlanActivityResourceText_QNAME = new QName("", "plan_activity_resource_text");
    private final static QName _PlanActivityModo_QNAME = new QName("", "plan_activity_modo");
    private final static QName _PlanActivityTitle_QNAME = new QName("", "plan_activity_title");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: glueps.adaptors.pp.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PlanAttribute }
     * 
     */
    public PlanAttribute createPlanAttribute() {
        return new PlanAttribute();
    }

    /**
     * Create an instance of {@link PlanBlocks }
     * 
     */
    public PlanBlocks createPlanBlocks() {
        return new PlanBlocks();
    }

    /**
     * Create an instance of {@link PlanActivityFields }
     * 
     */
    public PlanActivityFields createPlanActivityFields() {
        return new PlanActivityFields();
    }

    /**
     * Create an instance of {@link PlanBlock }
     * 
     */
    public PlanBlock createPlanBlock() {
        return new PlanBlock();
    }

    /**
     * Create an instance of {@link PlanActivities }
     * 
     */
    public PlanActivities createPlanActivities() {
        return new PlanActivities();
    }

    /**
     * Create an instance of {@link PlanActivityField }
     * 
     */
    public PlanActivityField createPlanActivityField() {
        return new PlanActivityField();
    }

    /**
     * Create an instance of {@link PlanTags }
     * 
     */
    public PlanTags createPlanTags() {
        return new PlanTags();
    }

    /**
     * Create an instance of {@link PlanTagAttribute }
     * 
     */
    public PlanTagAttribute createPlanTagAttribute() {
        return new PlanTagAttribute();
    }

    /**
     * Create an instance of {@link PlanActivityAttribute }
     * 
     */
    public PlanActivityAttribute createPlanActivityAttribute() {
        return new PlanActivityAttribute();
    }

    /**
     * Create an instance of {@link Pedplan }
     * 
     */
    public Pedplan createPedplan() {
        return new Pedplan();
    }

    /**
     * Create an instance of {@link PlanTag }
     * 
     */
    public PlanTag createPlanTag() {
        return new PlanTag();
    }

    /**
     * Create an instance of {@link PlanTagAttributes }
     * 
     */
    public PlanTagAttributes createPlanTagAttributes() {
        return new PlanTagAttributes();
    }

    /**
     * Create an instance of {@link PlanActivityFieldValue }
     * 
     */
    public PlanActivityFieldValue createPlanActivityFieldValue() {
        return new PlanActivityFieldValue();
    }

    /**
     * Create an instance of {@link PlanAttributes }
     * 
     */
    public PlanAttributes createPlanAttributes() {
        return new PlanAttributes();
    }

    /**
     * Create an instance of {@link PlanActivityType }
     * 
     */
    public PlanActivityType createPlanActivityType() {
        return new PlanActivityType();
    }

    /**
     * Create an instance of {@link PlanActivityAttributes }
     * 
     */
    public PlanActivityAttributes createPlanActivityAttributes() {
        return new PlanActivityAttributes();
    }

    /**
     * Create an instance of {@link PlanTagAttributeValues }
     * 
     */
    public PlanTagAttributeValues createPlanTagAttributeValues() {
        return new PlanTagAttributeValues();
    }

    /**
     * Create an instance of {@link PlanActivityResource }
     * 
     */
    public PlanActivityResource createPlanActivityResource() {
        return new PlanActivityResource();
    }

    /**
     * Create an instance of {@link PlanActivityAttributeName }
     * 
     */
    public PlanActivityAttributeName createPlanActivityAttributeName() {
        return new PlanActivityAttributeName();
    }

    /**
     * Create an instance of {@link PlanAttributeValue }
     * 
     */
    public PlanAttributeValue createPlanAttributeValue() {
        return new PlanAttributeValue();
    }

    /**
     * Create an instance of {@link PlanActivity }
     * 
     */
    public PlanActivity createPlanActivity() {
        return new PlanActivity();
    }

    /**
     * Create an instance of {@link PlanActivityResources }
     * 
     */
    public PlanActivityResources createPlanActivityResources() {
        return new PlanActivityResources();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_usecase")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPlanUsecase(String value) {
        return new JAXBElement<String>(_PlanUsecase_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_tag_attribute_title")
    public JAXBElement<String> createPlanTagAttributeTitle(String value) {
        return new JAXBElement<String>(_PlanTagAttributeTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_activity_opzattv")
    public JAXBElement<BigInteger> createPlanActivityOpzattv(BigInteger value) {
        return new JAXBElement<BigInteger>(_PlanActivityOpzattv_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_author")
    public JAXBElement<String> createPlanAuthor(String value) {
        return new JAXBElement<String>(_PlanAuthor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_tag_attribute_value")
    public JAXBElement<String> createPlanTagAttributeValue(String value) {
        return new JAXBElement<String>(_PlanTagAttributeValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_attribute_name")
    public JAXBElement<String> createPlanAttributeName(String value) {
        return new JAXBElement<String>(_PlanAttributeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_description")
    public JAXBElement<String> createPlanDescription(String value) {
        return new JAXBElement<String>(_PlanDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_title")
    public JAXBElement<String> createPlanTitle(String value) {
        return new JAXBElement<String>(_PlanTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_activity_field_name")
    public JAXBElement<String> createPlanActivityFieldName(String value) {
        return new JAXBElement<String>(_PlanActivityFieldName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_email")
    public JAXBElement<String> createPlanEmail(String value) {
        return new JAXBElement<String>(_PlanEmail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_tag_value")
    public JAXBElement<String> createPlanTagValue(String value) {
        return new JAXBElement<String>(_PlanTagValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_activity_order")
    public JAXBElement<BigInteger> createPlanActivityOrder(BigInteger value) {
        return new JAXBElement<BigInteger>(_PlanActivityOrder_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_tag_attribute_code")
    public JAXBElement<String> createPlanTagAttributeCode(String value) {
        return new JAXBElement<String>(_PlanTagAttributeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_activity_resource_link")
    public JAXBElement<String> createPlanActivityResourceLink(String value) {
        return new JAXBElement<String>(_PlanActivityResourceLink_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_activity_resource_text")
    public JAXBElement<String> createPlanActivityResourceText(String value) {
        return new JAXBElement<String>(_PlanActivityResourceText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_activity_modo")
    public JAXBElement<BigInteger> createPlanActivityModo(BigInteger value) {
        return new JAXBElement<BigInteger>(_PlanActivityModo_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plan_activity_title")
    public JAXBElement<String> createPlanActivityTitle(String value) {
        return new JAXBElement<String>(_PlanActivityTitle_QNAME, String.class, null, value);
    }

}
