//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.06 at 06:20:42 PM CET 
//


package glueps.adaptors.ld.pp.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}plan_usecase"/>
 *         &lt;element ref="{}plan_title"/>
 *         &lt;element ref="{}plan_author"/>
 *         &lt;element ref="{}plan_email"/>
 *         &lt;element ref="{}plan_description"/>
 *         &lt;element ref="{}plan_attributes"/>
 *         &lt;element ref="{}plan_tags"/>
 *         &lt;element ref="{}plan_blocks"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "planUsecase",
    "planTitle",
    "planAuthor",
    "planEmail",
    "planDescription",
    "planAttributes",
    "planTags",
    "planBlocks"
})
@XmlRootElement(name = "pedplan")
public class Pedplan {

    @XmlElement(name = "plan_usecase", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String planUsecase;
    @XmlElement(name = "plan_title", required = true)
    protected String planTitle;
    @XmlElement(name = "plan_author", required = true)
    protected String planAuthor;
    @XmlElement(name = "plan_email", required = true)
    protected String planEmail;
    @XmlElement(name = "plan_description", required = true)
    protected String planDescription;
    @XmlElement(name = "plan_attributes", required = true)
    protected PlanAttributes planAttributes;
    @XmlElement(name = "plan_tags", required = true)
    protected PlanTags planTags;
    @XmlElement(name = "plan_blocks", required = true)
    protected PlanBlocks planBlocks;
    @XmlAttribute(required = true)
    protected BigInteger id;

    /**
     * Gets the value of the planUsecase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanUsecase() {
        return planUsecase;
    }

    /**
     * Sets the value of the planUsecase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanUsecase(String value) {
        this.planUsecase = value;
    }

    /**
     * Gets the value of the planTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanTitle() {
        return planTitle;
    }

    /**
     * Sets the value of the planTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanTitle(String value) {
        this.planTitle = value;
    }

    /**
     * Gets the value of the planAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanAuthor() {
        return planAuthor;
    }

    /**
     * Sets the value of the planAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanAuthor(String value) {
        this.planAuthor = value;
    }

    /**
     * Gets the value of the planEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanEmail() {
        return planEmail;
    }

    /**
     * Sets the value of the planEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanEmail(String value) {
        this.planEmail = value;
    }

    /**
     * Gets the value of the planDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanDescription() {
        return planDescription;
    }

    /**
     * Sets the value of the planDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanDescription(String value) {
        this.planDescription = value;
    }

    /**
     * Gets the value of the planAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link PlanAttributes }
     *     
     */
    public PlanAttributes getPlanAttributes() {
        return planAttributes;
    }

    /**
     * Sets the value of the planAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanAttributes }
     *     
     */
    public void setPlanAttributes(PlanAttributes value) {
        this.planAttributes = value;
    }

    /**
     * Gets the value of the planTags property.
     * 
     * @return
     *     possible object is
     *     {@link PlanTags }
     *     
     */
    public PlanTags getPlanTags() {
        return planTags;
    }

    /**
     * Sets the value of the planTags property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanTags }
     *     
     */
    public void setPlanTags(PlanTags value) {
        this.planTags = value;
    }

    /**
     * Gets the value of the planBlocks property.
     * 
     * @return
     *     possible object is
     *     {@link PlanBlocks }
     *     
     */
    public PlanBlocks getPlanBlocks() {
        return planBlocks;
    }

    /**
     * Sets the value of the planBlocks property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanBlocks }
     *     
     */
    public void setPlanBlocks(PlanBlocks value) {
        this.planBlocks = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

}
