//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.06 at 06:20:42 PM CET 
//


package glueps.adaptors.ld.pp.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}plan_activity_resource_link"/>
 *         &lt;element ref="{}plan_activity_resource_text"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "planActivityResourceLink",
    "planActivityResourceText"
})
@XmlRootElement(name = "plan_activity_resource")
public class PlanActivityResource {

    @XmlElement(name = "plan_activity_resource_link", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String planActivityResourceLink;
    @XmlElement(name = "plan_activity_resource_text", required = true)
    protected String planActivityResourceText;

    /**
     * Gets the value of the planActivityResourceLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanActivityResourceLink() {
        return planActivityResourceLink;
    }

    /**
     * Sets the value of the planActivityResourceLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanActivityResourceLink(String value) {
        this.planActivityResourceLink = value;
    }

    /**
     * Gets the value of the planActivityResourceText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanActivityResourceText() {
        return planActivityResourceText;
    }

    /**
     * Sets the value of the planActivityResourceText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanActivityResourceText(String value) {
        this.planActivityResourceText = value;
    }

}
