//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.06 at 06:20:42 PM CET 
//


package glueps.adaptors.ld.pp.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}plan_tag_attribute_title"/>
 *         &lt;element ref="{}plan_tag_attribute_values"/>
 *       &lt;/sequence>
 *       &lt;attribute name="order" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "planTagAttributeTitle",
    "planTagAttributeValues"
})
@XmlRootElement(name = "plan_tag_attribute")
public class PlanTagAttribute {

    @XmlElement(name = "plan_tag_attribute_title", required = true)
    protected String planTagAttributeTitle;
    @XmlElement(name = "plan_tag_attribute_values", required = true)
    protected PlanTagAttributeValues planTagAttributeValues;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String order;

    /**
     * Gets the value of the planTagAttributeTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanTagAttributeTitle() {
        return planTagAttributeTitle;
    }

    /**
     * Sets the value of the planTagAttributeTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanTagAttributeTitle(String value) {
        this.planTagAttributeTitle = value;
    }

    /**
     * Gets the value of the planTagAttributeValues property.
     * 
     * @return
     *     possible object is
     *     {@link PlanTagAttributeValues }
     *     
     */
    public PlanTagAttributeValues getPlanTagAttributeValues() {
        return planTagAttributeValues;
    }

    /**
     * Sets the value of the planTagAttributeValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanTagAttributeValues }
     *     
     */
    public void setPlanTagAttributeValues(PlanTagAttributeValues value) {
        this.planTagAttributeValues = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrder(String value) {
        this.order = value;
    }

}
