//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.06 at 06:20:42 PM CET 
//


package glueps.adaptors.ld.pp.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}plan_tag_value"/>
 *         &lt;element ref="{}plan_tag_attributes"/>
 *       &lt;/sequence>
 *       &lt;attribute name="order" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "planTagValue",
    "planTagAttributes"
})
@XmlRootElement(name = "plan_tag")
public class PlanTag {

    @XmlElement(name = "plan_tag_value", required = true)
    protected String planTagValue;
    @XmlElement(name = "plan_tag_attributes", required = true)
    protected PlanTagAttributes planTagAttributes;
    @XmlAttribute(required = true)
    protected BigInteger order;

    /**
     * Gets the value of the planTagValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanTagValue() {
        return planTagValue;
    }

    /**
     * Sets the value of the planTagValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanTagValue(String value) {
        this.planTagValue = value;
    }

    /**
     * Gets the value of the planTagAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link PlanTagAttributes }
     *     
     */
    public PlanTagAttributes getPlanTagAttributes() {
        return planTagAttributes;
    }

    /**
     * Sets the value of the planTagAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanTagAttributes }
     *     
     */
    public void setPlanTagAttributes(PlanTagAttributes value) {
        this.planTagAttributes = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrder(BigInteger value) {
        this.order = value;
    }

}
