//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.06 at 06:20:42 PM CET 
//


package glueps.adaptors.ld.pp.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}plan_activity_field_name"/>
 *         &lt;element ref="{}plan_activity_field_value"/>
 *         &lt;element ref="{}plan_activity_resources" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="fid" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "planActivityFieldName",
    "planActivityFieldValue",
    "planActivityResources"
})
@XmlRootElement(name = "plan_activity_field")
public class PlanActivityField {

    @XmlElement(name = "plan_activity_field_name", required = true)
    protected String planActivityFieldName;
    @XmlElement(name = "plan_activity_field_value", required = true)
    protected PlanActivityFieldValue planActivityFieldValue;
    @XmlElement(name = "plan_activity_resources")
    protected PlanActivityResources planActivityResources;
    @XmlAttribute(required = true)
    protected BigInteger fid;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String type;

    /**
     * Gets the value of the planActivityFieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanActivityFieldName() {
        return planActivityFieldName;
    }

    /**
     * Sets the value of the planActivityFieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanActivityFieldName(String value) {
        this.planActivityFieldName = value;
    }

    /**
     * Gets the value of the planActivityFieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link PlanActivityFieldValue }
     *     
     */
    public PlanActivityFieldValue getPlanActivityFieldValue() {
        return planActivityFieldValue;
    }

    /**
     * Sets the value of the planActivityFieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanActivityFieldValue }
     *     
     */
    public void setPlanActivityFieldValue(PlanActivityFieldValue value) {
        this.planActivityFieldValue = value;
    }

    /**
     * Gets the value of the planActivityResources property.
     * 
     * @return
     *     possible object is
     *     {@link PlanActivityResources }
     *     
     */
    public PlanActivityResources getPlanActivityResources() {
        return planActivityResources;
    }

    /**
     * Sets the value of the planActivityResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanActivityResources }
     *     
     */
    public void setPlanActivityResources(PlanActivityResources value) {
        this.planActivityResources = value;
    }

    /**
     * Gets the value of the fid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFid() {
        return fid;
    }

    /**
     * Sets the value of the fid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFid(BigInteger value) {
        this.fid = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
