//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.06 at 06:20:42 PM CET 
//


package glueps.adaptors.ld.pp.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}plan_activity_attribute_name"/>
 *         &lt;element ref="{}plan_activity_fields"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "planActivityAttributeName",
    "planActivityFields"
})
@XmlRootElement(name = "plan_activity_attribute")
public class PlanActivityAttribute {

    @XmlElement(name = "plan_activity_attribute_name", required = true)
    protected PlanActivityAttributeName planActivityAttributeName;
    @XmlElement(name = "plan_activity_fields", required = true)
    protected PlanActivityFields planActivityFields;

    /**
     * Gets the value of the planActivityAttributeName property.
     * 
     * @return
     *     possible object is
     *     {@link PlanActivityAttributeName }
     *     
     */
    public PlanActivityAttributeName getPlanActivityAttributeName() {
        return planActivityAttributeName;
    }

    /**
     * Sets the value of the planActivityAttributeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanActivityAttributeName }
     *     
     */
    public void setPlanActivityAttributeName(PlanActivityAttributeName value) {
        this.planActivityAttributeName = value;
    }

    /**
     * Gets the value of the planActivityFields property.
     * 
     * @return
     *     possible object is
     *     {@link PlanActivityFields }
     *     
     */
    public PlanActivityFields getPlanActivityFields() {
        return planActivityFields;
    }

    /**
     * Sets the value of the planActivityFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanActivityFields }
     *     
     */
    public void setPlanActivityFields(PlanActivityFields value) {
        this.planActivityFields = value;
    }

}
