//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.06 at 06:20:42 PM CET 
//


package glueps.adaptors.ld.pp.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}plan_attribute_name"/>
 *         &lt;element ref="{}plan_attribute_value"/>
 *       &lt;/sequence>
 *       &lt;attribute name="plan_attribute_number" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="plan_attribute_type" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "planAttributeName",
    "planAttributeValue"
})
@XmlRootElement(name = "plan_attribute")
public class PlanAttribute {

    @XmlElement(name = "plan_attribute_name", required = true)
    protected String planAttributeName;
    @XmlElement(name = "plan_attribute_value", required = true)
    protected PlanAttributeValue planAttributeValue;
    @XmlAttribute(name = "plan_attribute_number", required = true)
    protected BigInteger planAttributeNumber;
    @XmlAttribute(name = "plan_attribute_type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String planAttributeType;

    /**
     * Gets the value of the planAttributeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanAttributeName() {
        return planAttributeName;
    }

    /**
     * Sets the value of the planAttributeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanAttributeName(String value) {
        this.planAttributeName = value;
    }

    /**
     * Gets the value of the planAttributeValue property.
     * 
     * @return
     *     possible object is
     *     {@link PlanAttributeValue }
     *     
     */
    public PlanAttributeValue getPlanAttributeValue() {
        return planAttributeValue;
    }

    /**
     * Sets the value of the planAttributeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanAttributeValue }
     *     
     */
    public void setPlanAttributeValue(PlanAttributeValue value) {
        this.planAttributeValue = value;
    }

    /**
     * Gets the value of the planAttributeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlanAttributeNumber() {
        return planAttributeNumber;
    }

    /**
     * Sets the value of the planAttributeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlanAttributeNumber(BigInteger value) {
        this.planAttributeNumber = value;
    }

    /**
     * Gets the value of the planAttributeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanAttributeType() {
        return planAttributeType;
    }

    /**
     * Sets the value of the planAttributeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanAttributeType(String value) {
        this.planAttributeType = value;
    }

}
