//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.06 at 06:20:42 PM CET 
//


package glueps.adaptors.ld.pp.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}plan_activity_title"/>
 *         &lt;element ref="{}plan_activity_order"/>
 *         &lt;element ref="{}plan_activity_type"/>
 *         &lt;element ref="{}plan_activity_modo"/>
 *         &lt;element ref="{}plan_activity_opzattv"/>
 *         &lt;element ref="{}plan_activity_attributes"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "planActivityTitle",
    "planActivityOrder",
    "planActivityType",
    "planActivityModo",
    "planActivityOpzattv",
    "planActivityAttributes"
})
@XmlRootElement(name = "plan_activity")
public class PlanActivity {

    @XmlElement(name = "plan_activity_title", required = true)
    protected String planActivityTitle;
    @XmlElement(name = "plan_activity_order", required = true)
    protected BigInteger planActivityOrder;
    @XmlElement(name = "plan_activity_type", required = true)
    protected PlanActivityType planActivityType;
    @XmlElement(name = "plan_activity_modo", required = true)
    protected BigInteger planActivityModo;
    @XmlElement(name = "plan_activity_opzattv", required = true)
    protected BigInteger planActivityOpzattv;
    @XmlElement(name = "plan_activity_attributes", required = true)
    protected PlanActivityAttributes planActivityAttributes;
    @XmlAttribute(required = true)
    protected BigInteger id;

    /**
     * Gets the value of the planActivityTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanActivityTitle() {
        return planActivityTitle;
    }

    /**
     * Sets the value of the planActivityTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanActivityTitle(String value) {
        this.planActivityTitle = value;
    }

    /**
     * Gets the value of the planActivityOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlanActivityOrder() {
        return planActivityOrder;
    }

    /**
     * Sets the value of the planActivityOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlanActivityOrder(BigInteger value) {
        this.planActivityOrder = value;
    }

    /**
     * Gets the value of the planActivityType property.
     * 
     * @return
     *     possible object is
     *     {@link PlanActivityType }
     *     
     */
    public PlanActivityType getPlanActivityType() {
        return planActivityType;
    }

    /**
     * Sets the value of the planActivityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanActivityType }
     *     
     */
    public void setPlanActivityType(PlanActivityType value) {
        this.planActivityType = value;
    }

    /**
     * Gets the value of the planActivityModo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlanActivityModo() {
        return planActivityModo;
    }

    /**
     * Sets the value of the planActivityModo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlanActivityModo(BigInteger value) {
        this.planActivityModo = value;
    }

    /**
     * Gets the value of the planActivityOpzattv property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlanActivityOpzattv() {
        return planActivityOpzattv;
    }

    /**
     * Sets the value of the planActivityOpzattv property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlanActivityOpzattv(BigInteger value) {
        this.planActivityOpzattv = value;
    }

    /**
     * Gets the value of the planActivityAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link PlanActivityAttributes }
     *     
     */
    public PlanActivityAttributes getPlanActivityAttributes() {
        return planActivityAttributes;
    }

    /**
     * Sets the value of the planActivityAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanActivityAttributes }
     *     
     */
    public void setPlanActivityAttributes(PlanActivityAttributes value) {
        this.planActivityAttributes = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

}
