/*******************************************************************************
 * Copyright (C) 2015 Intelligent & Cooperative Systems Research Group/Education,
 * Media, Computing & Culture (GSIC-EMIC). University of Valladolid(UVA). 
 * Valladolid, Spain. https://www.gsic.uva.es/
 * 
 * This file is part of Glue!PS.
 * 
 * Glue!PS is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or 
 * (at your option) any later version.
 * 
 * Glue!PS is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.15 at 11:06:38 AM CEST 
//


package glueps.adaptors.ld.imsld.icollage.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}uol-info"/>
 *         &lt;element ref="{}role-root"/>
 *         &lt;element ref="{}role-population"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uolInfo",
    "roleRoot",
    "rolePopulation"
})
@XmlRootElement(name = "icollage-manifest")
public class IcollageManifest {

    @XmlElement(name = "uol-info", required = true)
    protected UolInfo uolInfo;
    @XmlElement(name = "role-root", required = true)
    protected RoleRoot roleRoot;
    @XmlElement(name = "role-population", required = true)
    protected RolePopulation rolePopulation;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the uolInfo property.
     * 
     * @return
     *     possible object is
     *     {@link UolInfo }
     *     
     */
    public UolInfo getUolInfo() {
        return uolInfo;
    }

    /**
     * Sets the value of the uolInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link UolInfo }
     *     
     */
    public void setUolInfo(UolInfo value) {
        this.uolInfo = value;
    }

    /**
     * Gets the value of the roleRoot property.
     * 
     * @return
     *     possible object is
     *     {@link RoleRoot }
     *     
     */
    public RoleRoot getRoleRoot() {
        return roleRoot;
    }

    /**
     * Sets the value of the roleRoot property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleRoot }
     *     
     */
    public void setRoleRoot(RoleRoot value) {
        this.roleRoot = value;
    }

    /**
     * Gets the value of the rolePopulation property.
     * 
     * @return
     *     possible object is
     *     {@link RolePopulation }
     *     
     */
    public RolePopulation getRolePopulation() {
        return rolePopulation;
    }

    /**
     * Sets the value of the rolePopulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RolePopulation }
     *     
     */
    public void setRolePopulation(RolePopulation value) {
        this.rolePopulation = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
