//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.15 at 11:06:38 AM CEST 
//


package glueps.adaptors.ld.imsld.icollage.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the icollage package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Title_QNAME = new QName("", "title");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: icollage
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RoleRoot }
     * 
     */
    public RoleRoot createRoleRoot() {
        return new RoleRoot();
    }

    /**
     * Create an instance of {@link RoleOccurrenceRef }
     * 
     */
    public RoleOccurrenceRef createRoleOccurrenceRef() {
        return new RoleOccurrenceRef();
    }

    /**
     * Create an instance of {@link RolePopulation }
     * 
     */
    public RolePopulation createRolePopulation() {
        return new RolePopulation();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link UolInfo }
     * 
     */
    public UolInfo createUolInfo() {
        return new UolInfo();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link IcollageManifest }
     * 
     */
    public IcollageManifest createIcollageManifest() {
        return new IcollageManifest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

}
